### PR TITLE
Fix 1353

### LINKED ISSUE #1353: Delve should support more ways of specifying debuginfo location
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.1.0
2. What version of Go are you using? (`go version`)?
1.10.4
3. What operating system and processor architecture are you using?
Fedora 28 x64
4. What did you do?
Tried to load external debug info in Delve.
5. What did you expect to see?
Expected to be able to either place the debuginfo in the same directory as the binary or, better yet, to be able to specify the directory to read debuginfo out of. 

6. What did you see instead?
GDB allows searching for debuginfo in multiple locations (https://www-zeuthen.desy.de/unix/unixguide/infohtml/gdb/Separate-Debug-Files.html). Currently Delve only looks in /usr/lib/debug/.build.id/*/*. The ability to specify a debug file directory would allow delve to read debuginfo even when the user doesn't have permission to write to /usr/lib/debug. It could also be useful to support the other debug info locations, for example, to have a consistent location to find a binary regardless of the build-id.

### PR DESCRIPTION
**Pull request by derekparker**
Adds a config file option to allow specifying a list of directories to
search in when looking for seperate external debug info files.

Fixes #1353

### CODE REVIEW

File: pkg/proc/gdbserial/gdbserver.go [hunk 1]
```diff
@@ -512,32 +512,32 @@ func LLDBAttach(pid int, path string) (*Process, error) {
...
+	process.SysProcAttr = sysProcAttr(false)
 
-	err := proc.Start()
+	err := process.Start()
 	if err != nil {
 		return nil, err
 	}
 
-	p := New(proc.Process)
+	p := &Process{}
```
Comment (aarzilli) [inline pkg/proc/gdbserial/gdbserver.go]: The call to `New` is needed here, it initializes a bunch of things. Should be `p := New(process.Process)` after the rename.

Comment (derekparker) [reply pkg/proc/gdbserial/gdbserver.go]: Fixed... the pattern matching in my brain confused that with the builtin `new`, heh.
