### PR TITLE
proc: replace cgo with syscalls on windows

### LINKED ISSUE #409: dlv.exe is crashing with "bad pointer in frame github.com/derekparker/delve/proc.registers" on windows
To reproduce

```
C:\dev\src\t>c:\dev\bin\dlv version
Delve Debugger
Version: 0.11.0-alpha
Build:

C:\dev\src\t>go version
go version devel +41191e1 Mon Feb 8 23:10:00 2016 +0000 windows/amd64

C:\dev\src\t>type main.go
package main

import (
        "fmt"
)

func main() {
        for i := 0; i < 10; i++ {
                fmt.Printf("i=%d\n", i)
        }
}

C:\dev\src\t>c:\dev\bin\dlv debug
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x401066 for main.main c:/dev/src/t/main.go:8
(dlv) c
runtime: bad pointer in frame github.com/derekparker/delve/proc.registers at 0xc08205f5e0: 0x1bc
fatal error: invalid stack pointer

runtime stack:
runtime.throw(0xb99030, 0x15)
	C:/dev/go/src/runtime/panic.go:530 +0x97 fp=0x184f6d8 sp=0x184f6c0
runtime.adjustpointers(0xc08205f5b8, 0x184f858, 0x184fb70, 0xd4c978)
	C:/dev/go/src/runtime/stack.go:579 +0x2e2 fp=0x184f7d0 sp=0x184f6d8
runtime.adjustframe(0x184fa90, 0x184fb70, 0x184f901)
	C:/dev/go/src/runtime/stack.go:644 +0x1d2 fp=0x184f890 sp=0x184f7d0
runtime.gentraceback(0x407e70, 0xc08205f328, 0x0, 0xc082598180, 0x0, 0x0, 0x7fffffff, 0xc42568, 0x184fb70, 0x0, ...)
	C:/dev/go/src/runtime/traceback.go:369 +0xda3 fp=0x184fae8 sp=0x184f890
runtime.copystack(0xc082598180, 0x4000)
	C:/dev/go/src/runtime/stack.go:759 +0x1c5 fp=0x184fcd8 sp=0x184fae8
runtime.newstack()
	C:/dev/go/src/runtime/stack.go:947 +0xb5b fp=0x184fe48 sp=0x184fcd8
runtime.morestack()
	C:/dev/go/src/runtime/asm_amd64.s:359 +0x87 fp=0x184fe50 sp=0x184fe48

goroutine 21 [copystack]:
runtime.cgoCheckArg(0x93e260, 0xc082166760, 0x1, 0xbdd0c0, 0x29)
	C:/dev/go/src/runtime/cgocall.go:402 fp=0xc08205f330 sp=0xc08205f328
runtime.cgoCheckArg(0xa59de0, 0xc082166760, 0xc081ff0001, 0xbdd0c0, 0x29)
	C:/dev/go/src/runtime/cgocall.go:488 +0x904 fp=0xc08205f428 sp=0xc08205f330
runtime.cgoCheckArg(0xab6540, 0xc082166750, 0x1, 0xbdd0c0, 0x29)
	C:/dev/go/src/runtime/cgocall.go:488 +0x904 fp=0xc08205f520 sp=0xc08205f428
runtime.cgoCheckPointer(0x9155a0, 0xc082166750, 0xc082113f70, 0x1, 0x1, 0x0, 0x0)
	C:/dev/go/src/runtime/cgocall.go:373 +0x1ac fp=0xc08205f570 sp=0xc08205f520
github.com/derekparker/delve/proc.registers(0xc08200de00, 0x0, 0x0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/proc/registers_windows_amd64.go:125 +0x2a7 fp=0xc08205f618 sp=0xc08205f570
github.com/derekparker/delve/proc.(*Thread).Registers(0xc08200de00, 0x0, 0x0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/proc/registers.go:20 +0x5b fp=0xc08205f6b0 sp=0xc08205f618
github.com/derekparker/delve/proc.(*Thread).PC(0xc08200de00, 0x0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/proc/registers.go:29 +0x38 fp=0xc08205f700 sp=0xc08205f6b0
github.com/derekparker/delve/proc.(*Thread).SetCurrentBreakpoint(0xc08200de00, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/proc/threads.go:360 +0x47 fp=0xc08205f780 sp=0xc08205f700
github.com/derekparker/delve/proc.(*Process).setCurrentBreakpoints(0xc0820788c0, 0xc08200de00, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/proc/proc_windows.go:458 +0x34 fp=0xc08205f7a0 sp=0xc08205f780
github.com/derekparker/delve/proc.(*Process).Continue(0xc0820788c0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/proc/proc.go:393 +0x208 fp=0xc08205f880 sp=0xc08205f7a0
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc0821122e0, 0xc0821c83c0, 0x0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/service/debugger/debugger.go:261 +0x785 fp=0xc08205f9e0 sp=0xc08205f880
github.com/derekparker/delve/service/rpc.(*RPCServer).Command(0xc082109740, 0xc0821c83c0, 0xc08267f130, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/service/rpc/server.go:107 +0x46 fp=0xc08205fa20 sp=0xc08205f9e0
runtime.call64(0xc082588440, 0xaf8378, 0xc0821666f0, 0x1800000028)
	C:/dev/go/src/runtime/asm_amd64.s:473 +0x45 fp=0xc08205fa68 sp=0xc08205fa20
reflect.Value.call(0x9fc880, 0xaf8378, 0x13, 0xb1ada0, 0x4, 0xc08205fee8, 0x3, 0x3, 0x0, 0x0, ...)
	C:/dev/go/src/reflect/value.go:435 +0x1214 fp=0xc08205fdb8 sp=0xc08205fa68
reflect.Value.Call(0x9fc880, 0xaf8378, 0x13, 0xc08205fee8, 0x3, 0x3, 0x0, 0x0, 0x0)
	C:/dev/go/src/reflect/value.go:303 +0xb8 fp=0xc08205fe18 sp=0xc08205fdb8
net/rpc.(*service).call(0xc082141b00, 0xc082141ac0, 0xc082112ca8, 0xc08206ec00, 0xc0821e0300, 0x9159c0, 0xc0821c83c0, 0x16, 0x915a20, 0xc08267f130, ...)
	C:/dev/go/src/net/rpc/server.go:383 +0x1c9 fp=0xc08205ff38 sp=0xc08205fe18
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc08205ff40 sp=0xc08205ff38
created by net/rpc.(*Server).ServeCodec
	C:/dev/go/src/net/rpc/server.go:477 +0x4a4

goroutine 1 [chan receive]:
runtime.gopark(0xc427f0, 0xc0822b99d8, 0xb317d0, 0xc, 0x17, 0x3)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc0826256e8 sp=0xc0826256c0
runtime.goparkunlock(0xc0822b99d8, 0xb317d0, 0xc, 0x508e17, 0x3)
	C:/dev/go/src/runtime/proc.go:268 +0x5b fp=0xc082625720 sp=0xc0826256e8
runtime.chanrecv(0x92f520, 0xc0822b9980, 0xc0826257f8, 0xc0822b9901, 0xc0822b0000)
	C:/dev/go/src/runtime/chan.go:470 +0x4ad fp=0xc0826257a8 sp=0xc082625720
runtime.chanrecv2(0x92f520, 0xc0822b9980, 0xc0826257f8, 0x2)
	C:/dev/go/src/runtime/chan.go:360 +0x2b fp=0xc0826257d8 sp=0xc0826257a8
github.com/derekparker/delve/terminal.cont(0xc08267ec80, 0x0, 0x0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/terminal/command.go:457 +0x8b fp=0xc082625820 sp=0xc0826257d8
github.com/derekparker/delve/terminal.(*Term).Run(0xc08267ec80, 0x0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/terminal/terminal.go:117 +0xac7 fp=0xc082625a48 sp=0xc082625820
main.execute(0x0, 0xc082112260, 0x1, 0x1, 0xc08201c0e8, 0x0)
	c:/dev/src/github.com/derekparker/delve/cmd/dlv/main.go:362 +0x814 fp=0xc082625bc8 sp=0xc082625a48
main.debugCmd.func1(0xe7e9b0, 0x0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/cmd/dlv/main.go:204 +0x371 fp=0xc082625ca8 sp=0xc082625bc8
main.debugCmd(0xc0821065a0, 0xe7e9b0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/cmd/dlv/main.go:190 +0x3c fp=0xc082625cd0 sp=0xc082625ca8
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc0821065a0, 0xe7e9b0, 0x0, 0x0, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:547 +0x861 fp=0xc082625de8 sp=0xc082625cd0
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc082106000, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:630 +0x593 fp=0xc082625f00 sp=0xc082625de8
main.main()
	c:/dev/src/github.com/derekparker/delve/cmd/dlv/main.go:186 +0x43 fp=0xc082625f20 sp=0xc082625f00
runtime.main()
	C:/dev/go/src/runtime/proc.go:188 +0x27e fp=0xc082625f70 sp=0xc082625f20
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082625f78 sp=0xc082625f70

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc08201bfa8 sp=0xc08201bfa0

goroutine 2 [force gc (idle)]:
runtime.gopark(0xc427f0, 0xe60fe0, 0xb341e0, 0xf, 0x14, 0x1)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc082019f38 sp=0xc082019f10
runtime.goparkunlock(0xe60fe0, 0xb341e0, 0xf, 0xc082012014, 0x1)
	C:/dev/go/src/runtime/proc.go:268 +0x5b fp=0xc082019f70 sp=0xc082019f38
runtime.forcegchelper()
	C:/dev/go/src/runtime/proc.go:229 +0xc6 fp=0xc082019fa0 sp=0xc082019f70
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082019fa8 sp=0xc082019fa0
created by runtime.init.4
	C:/dev/go/src/runtime/proc.go:218 +0x32

goroutine 3 [GC sweep wait]:
runtime.gopark(0xc427f0, 0xe61180, 0xb29700, 0xd, 0x456214, 0x1)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc082015f28 sp=0xc082015f00
runtime.goparkunlock(0xe61180, 0xb29700, 0xd, 0x14, 0x1)
	C:/dev/go/src/runtime/proc.go:268 +0x5b fp=0xc082015f60 sp=0xc082015f28
runtime.bgsweep(0xc082028000)
	C:/dev/go/src/runtime/mgcsweep.go:79 +0x15b fp=0xc082015f98 sp=0xc082015f60
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082015fa0 sp=0xc082015f98
created by runtime.gcenable
	C:/dev/go/src/runtime/mgc.go:191 +0x5a

goroutine 4 [finalizer wait]:
runtime.gopark(0xc427f0, 0xe7e8c8, 0xb33ca0, 0xe, 0x14, 0x1)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc082017ef8 sp=0xc082017ed0
runtime.goparkunlock(0xe7e8c8, 0xb33ca0, 0xe, 0x2000000014, 0x1)
	C:/dev/go/src/runtime/proc.go:268 +0x5b fp=0xc082017f30 sp=0xc082017ef8
runtime.runfinq()
	C:/dev/go/src/runtime/mfinal.go:158 +0xb8 fp=0xc082017fa0 sp=0xc082017f30
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082017fa8 sp=0xc082017fa0
created by runtime.createfing
	C:/dev/go/src/runtime/mfinal.go:139 +0x67

goroutine 5 [syscall]:
runtime.notetsleepg(0xe7ec00, 0xffffffffffffffff, 0x1)
	C:/dev/go/src/runtime/lock_sema.go:257 +0x77 fp=0xc082061f20 sp=0xc082061ee0
os/signal.signal_recv(0x0)
	C:/dev/go/src/runtime/sigqueue.go:116 +0x139 fp=0xc082061f58 sp=0xc082061f20
os/signal.loop()
	C:/dev/go/src/os/signal/signal_unix.go:22 +0x1f fp=0xc082061fa0 sp=0xc082061f58
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082061fa8 sp=0xc082061fa0
created by os/signal.init.1
	C:/dev/go/src/os/signal/signal_unix.go:28 +0x3e

goroutine 7 [timer goroutine (idle)]:
runtime.gopark(0xc427f0, 0xe61200, 0xb9f450, 0x16, 0x14, 0x1)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc082063ee0 sp=0xc082063eb8
runtime.goparkunlock(0xe61200, 0xb9f450, 0x16, 0xc08202a414, 0x1)
	C:/dev/go/src/runtime/proc.go:268 +0x5b fp=0xc082063f18 sp=0xc082063ee0
runtime.timerproc()
	C:/dev/go/src/runtime/time.go:202 +0x131 fp=0xc082063fa0 sp=0xc082063f18
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082063fa8 sp=0xc082063fa0
created by runtime.addtimerLocked
	C:/dev/go/src/runtime/time.go:116 +0x126

goroutine 8 [chan receive, locked to thread]:
runtime.gopark(0xc427f0, 0xc08210f798, 0xb317d0, 0xc, 0x17, 0x3)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc08205de58 sp=0xc08205de30
runtime.goparkunlock(0xc08210f798, 0xb317d0, 0xc, 0xc0820da817, 0x3)
	C:/dev/go/src/runtime/proc.go:268 +0x5b fp=0xc08205de90 sp=0xc08205de58
runtime.chanrecv(0x92f8e0, 0xc08210f740, 0xc08205df68, 0x5f4201, 0x0)
	C:/dev/go/src/runtime/chan.go:470 +0x4ad fp=0xc08205df18 sp=0xc08205de90
runtime.chanrecv2(0x92f8e0, 0xc08210f740, 0xc08205df68, 0x1)
	C:/dev/go/src/runtime/chan.go:360 +0x2b fp=0xc08205df48 sp=0xc08205df18
github.com/derekparker/delve/proc.(*Process).handlePtraceFuncs(0xc0820788c0)
	c:/dev/src/github.com/derekparker/delve/proc/proc.go:783 +0xd8 fp=0xc08205df98 sp=0xc08205df48
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc08205dfa0 sp=0xc08205df98
created by github.com/derekparker/delve/proc.New
	c:/dev/src/github.com/derekparker/delve/proc/proc.go:78 +0x1e0

goroutine 15 [IO wait]:
runtime.gopark(0xc427b0, 0x325a70, 0xb1ba50, 0x7, 0xc082013d1b, 0x5)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc082023830 sp=0xc082023808
runtime.netpollblock(0x325a48, 0x72, 0xc082013d60)
	C:/dev/go/src/runtime/netpoll.go:341 +0x165 fp=0xc082023878 sp=0xc082023830
net.runtime_pollWait(0x325a48, 0x72, 0xc082113ce0)
	C:/dev/go/src/runtime/netpoll.go:160 +0x67 fp=0xc082023898 sp=0xc082023878
net.(*pollDesc).Wait(0xc082013df0, 0x72, 0x0, 0x0)
	C:/dev/go/src/net/fd_poll_runtime.go:73 +0x41 fp=0xc0820238b8 sp=0xc082023898
net.(*ioSrv).ExecIO(0xc08201c120, 0xc082013ce0, 0xb1d6a8, 0x7, 0xc420a8, 0x199, 0x0, 0x0)
	C:/dev/go/src/net/fd_windows.go:183 +0x177 fp=0xc082023998 sp=0xc0820238b8
net.(*netFD).Read(0xc082013c80, 0xc082594601, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	C:/dev/go/src/net/fd_windows.go:482 +0x17e fp=0xc082023a90 sp=0xc082023998
net.(*conn).Read(0xc08201c000, 0xc082594601, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	C:/dev/go/src/net/net.go:172 +0xeb fp=0xc082023af8 sp=0xc082023a90
encoding/json.(*Decoder).refill(0xc08202e000, 0x0, 0x0)
	C:/dev/go/src/encoding/json/stream.go:152 +0x28e fp=0xc082023bb0 sp=0xc082023af8
encoding/json.(*Decoder).readValue(0xc08202e000, 0x1, 0x0, 0x0)
	C:/dev/go/src/encoding/json/stream.go:128 +0x41a fp=0xc082023c60 sp=0xc082023bb0
encoding/json.(*Decoder).Decode(0xc08202e000, 0xa22620, 0xc08206ea48, 0x0, 0x0)
	C:/dev/go/src/encoding/json/stream.go:57 +0x160 fp=0xc082023ce0 sp=0xc082023c60
net/rpc/jsonrpc.(*clientCodec).ReadResponseHeader(0xc08206ea00, 0xc0820f4690, 0x0, 0x0)
	C:/dev/go/src/net/rpc/jsonrpc/client.go:75 +0x96 fp=0xc082023d98 sp=0xc082023ce0
net/rpc.(*Client).input(0xc0822b93e0)
	C:/dev/go/src/net/rpc/client.go:109 +0xc6 fp=0xc082023f88 sp=0xc082023d98
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082023f90 sp=0xc082023f88
created by net/rpc.NewClientWithCodec
	C:/dev/go/src/net/rpc/client.go:201 +0xde

goroutine 13 [GC worker (idle)]:
runtime.gopark(0xc082603800, 0xc08224df80, 0xb882b0, 0x10, 0x14, 0x0)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc08224df20 sp=0xc08224def8
runtime.gcBgMarkWorker(0xc08200e000)
	C:/dev/go/src/runtime/mgc.go:1402 +0xef fp=0xc08224df98 sp=0xc08224df20
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc08224dfa0 sp=0xc08224df98
created by runtime.gcBgMarkStartWorkers
	C:/dev/go/src/runtime/mgc.go:1329 +0x99

goroutine 14 [IO wait]:
runtime.gopark(0xc427b0, 0x3259b0, 0xb1ba50, 0x7, 0xc082013e1b, 0x5)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc082027680 sp=0xc082027658
runtime.netpollblock(0x325988, 0x72, 0xc082013ee0)
	C:/dev/go/src/runtime/netpoll.go:341 +0x165 fp=0xc0820276c8 sp=0xc082027680
net.runtime_pollWait(0x325988, 0x72, 0xc082113ee8)
	C:/dev/go/src/runtime/netpoll.go:160 +0x67 fp=0xc0820276e8 sp=0xc0820276c8
net.(*pollDesc).Wait(0xc082013f70, 0x72, 0x0, 0x0)
	C:/dev/go/src/net/fd_poll_runtime.go:73 +0x41 fp=0xc082027708 sp=0xc0820276e8
net.(*ioSrv).ExecIO(0xc08201c120, 0xc082013e60, 0xb1d6a8, 0x7, 0xc420a8, 0xc082113ec0, 0x0, 0x0)
	C:/dev/go/src/net/fd_windows.go:183 +0x177 fp=0xc0820277e8 sp=0xc082027708
net.(*netFD).Read(0xc082013e00, 0xc082594001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	C:/dev/go/src/net/fd_windows.go:482 +0x17e fp=0xc0820278e0 sp=0xc0820277e8
net.(*conn).Read(0xc08201c020, 0xc082594001, 0x5ff, 0x5ff, 0x0, 0x0, 0x0)
	C:/dev/go/src/net/net.go:172 +0xeb fp=0xc082027948 sp=0xc0820278e0
encoding/json.(*Decoder).refill(0xc08202e340, 0x0, 0x0)
	C:/dev/go/src/encoding/json/stream.go:152 +0x28e fp=0xc082027a00 sp=0xc082027948
encoding/json.(*Decoder).readValue(0xc08202e340, 0x1, 0x0, 0x0)
	C:/dev/go/src/encoding/json/stream.go:128 +0x41a fp=0xc082027ab0 sp=0xc082027a00
encoding/json.(*Decoder).Decode(0xc08202e340, 0xa226c0, 0xc0822b94c0, 0x0, 0x0)
	C:/dev/go/src/encoding/json/stream.go:57 +0x160 fp=0xc082027b30 sp=0xc082027ab0
net/rpc/jsonrpc.(*serverCodec).ReadRequestHeader(0xc0822b94a0, 0xc0821e1320, 0x0, 0x0)
	C:/dev/go/src/net/rpc/jsonrpc/server.go:66 +0x83 fp=0xc082027b80 sp=0xc082027b30
net/rpc.(*Server).readRequestHeader(0xc082141ac0, 0x344348, 0xc0822b94a0, 0x0, 0x0, 0xc0821e1320, 0xc082027c00, 0x0, 0x0)
	C:/dev/go/src/net/rpc/server.go:576 +0x97 fp=0xc082027c88 sp=0xc082027b80
net/rpc.(*Server).readRequest(0xc082141ac0, 0x344348, 0xc0822b94a0, 0xc082141ac0, 0xc082112ca8, 0xc08206ec00, 0x0, 0x0, 0x0, 0x0, ...)
	C:/dev/go/src/net/rpc/server.go:543 +0x92 fp=0xc082027d00 sp=0xc082027c88
net/rpc.(*Server).ServeCodec(0xc082141ac0, 0x344348, 0xc0822b94a0)
	C:/dev/go/src/net/rpc/server.go:462 +0x84 fp=0xc082027e40 sp=0xc082027d00
github.com/derekparker/delve/service/rpc.(*ServerImpl).Run.func1(0xc08201c138)
	c:/dev/src/github.com/derekparker/delve/service/rpc/server.go:72 +0x50b fp=0xc082027f88 sp=0xc082027e40
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc082027f90 sp=0xc082027f88
created by github.com/derekparker/delve/service/rpc.(*ServerImpl).Run
	c:/dev/src/github.com/derekparker/delve/service/rpc/server.go:73 +0x129

goroutine 16 [chan receive]:
runtime.gopark(0xc427f0, 0xc0822b9498, 0xb317d0, 0xc, 0x17, 0x3)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc08224bdc0 sp=0xc08224bd98
runtime.goparkunlock(0xc0822b9498, 0xb317d0, 0xc, 0x17, 0x3)
	C:/dev/go/src/runtime/proc.go:268 +0x5b fp=0xc08224bdf8 sp=0xc08224bdc0
runtime.chanrecv(0x9300c0, 0xc0822b9440, 0xc08224bf60, 0x1, 0x0)
	C:/dev/go/src/runtime/chan.go:470 +0x4ad fp=0xc08224be80 sp=0xc08224bdf8
runtime.chanrecv2(0x9300c0, 0xc0822b9440, 0xc08224bf60, 0x0)
	C:/dev/go/src/runtime/chan.go:360 +0x2b fp=0xc08224beb0 sp=0xc08224be80
github.com/derekparker/delve/terminal.(*Term).Run.func1(0xc0822b9440, 0xc08267ec80)
	c:/dev/src/github.com/derekparker/delve/terminal/terminal.go:56 +0x77 fp=0xc08224bf90 sp=0xc08224beb0
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc08224bf98 sp=0xc08224bf90
created by github.com/derekparker/delve/terminal.(*Term).Run
	c:/dev/src/github.com/derekparker/delve/terminal/terminal.go:62 +0x1d4

goroutine 20 [chan receive]:
runtime.gopark(0xc427f0, 0xc0822b9a38, 0xb317d0, 0xc, 0x17, 0x3)
	C:/dev/go/src/runtime/proc.go:262 +0x17c fp=0xc0821c3d00 sp=0xc0821c3cd8
runtime.goparkunlock(0xc0822b9a38, 0xb317d0, 0xc, 0x17, 0x3)
	C:/dev/go/src/runtime/proc.go:268 +0x5b fp=0xc0821c3d38 sp=0xc0821c3d00
runtime.chanrecv(0x92f7c0, 0xc0822b99e0, 0xc0821c3e38, 0xc08205fe01, 0x0)
	C:/dev/go/src/runtime/chan.go:470 +0x4ad fp=0xc0821c3dc0 sp=0xc0821c3d38
runtime.chanrecv1(0x92f7c0, 0xc0822b99e0, 0xc0821c3e38)
	C:/dev/go/src/runtime/chan.go:355 +0x2b fp=0xc0821c3df0 sp=0xc0821c3dc0
net/rpc.(*Client).Call(0xc0822b93e0, 0xc0821c8140, 0x11, 0x9159c0, 0xc0821c80e0, 0x915a20, 0xc08267f090, 0x0, 0x0)
	C:/dev/go/src/net/rpc/client.go:315 +0xd4 fp=0xc0821c3e48 sp=0xc0821c3df0
github.com/derekparker/delve/service/rpc.(*RPCClient).call(0xc082146300, 0xb1af58, 0x7, 0x9159c0, 0xc0821c80e0, 0x915a20, 0xc08267f090, 0x0, 0x0)
	c:/dev/src/github.com/derekparker/delve/service/rpc/client.go:254 +0xbb fp=0xc0821c3e98 sp=0xc0821c3e48
github.com/derekparker/delve/service/rpc.(*RPCClient).Continue.func1(0xc082146300, 0xc0822b9980)
	c:/dev/src/github.com/derekparker/delve/service/rpc/client.go:60 +0xe2 fp=0xc0821c3f80 sp=0xc0821c3e98
runtime.goexit()
	C:/dev/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc0821c3f88 sp=0xc0821c3f80
created by github.com/derekparker/delve/service/rpc.(*RPCClient).Continue
	c:/dev/src/github.com/derekparker/delve/service/rpc/client.go:88 +0x64

C:\dev\src\t>
```

I think it is crashing because latest version of Go has stricter cgo rules (see https://tip.golang.org/doc/go1.6#cgo for details). And, indeed, setting GODEBUG=cgocheck=0 environment variable makes crash go away.

Alex

### PR DESCRIPTION
**Pull request by alexbrainman**
Unrelated to conversion, I have also changed (*Thread).readMemory
to return only first count bytes of memory just as advised
by ReadProcessMemory.

Fixes #409

@lukehoban for your review. Thank you.
Sorry about the size of this change. I tried to make it as small as possible.

### CODE REVIEW

File: proc/syscall_windows.go [hunk 1]
```diff
@@ -22,8 +22,53 @@ type _THREAD_BASIC_INFORMATION struct {
 	BasePriority   int32
 }
 
+type _CREATE_PROCESS_DEBUG_INFO struct {
```
Comment (lukehoban) [inline proc/syscall_windows.go]: Juts a question - is this leading `_` conventional for syscalls?  I don't think I've seen it used in this way before.  That said - it seems fine in this context to distinguish the Win32 structs and API wrappers.

File: proc/syscall_windows.go [hunk 2]
```diff
@@ -22,8 +22,53 @@ type _THREAD_BASIC_INFORMATION struct {
...
+	File                syscall.Handle
+	Process             syscall.Handle
+	Thread              syscall.Handle
+	BaseOfImage         uintptr
+	DebugInfoFileOffset uint16
+	DebugInfoSize       uint16
```
Comment (lukehoban) [inline proc/syscall_windows.go]: `DebugInfoFileOffset` and `DebugInfoSize` are `DWORD`s, right?  https://msdn.microsoft.com/en-us/library/windows/desktop/ms679286(v=vs.85).aspx.  Delve isn't using anything in this struct past the `Thread` field, so likely this isn't causing any problems yet.

File: proc/syscall_windows.go [hunk 3]
```diff
@@ -22,8 +22,53 @@ type _THREAD_BASIC_INFORMATION struct {
...
+	ThreadLocalBase     uintptr
+	StartAddress        uintptr
+	ImageName           *byte
```
Comment (lukehoban) [inline proc/syscall_windows.go]: Any reason this is `*byte` instead of `uintptr`?  In particular, this pointer is in the address space of the debuggee, so can't be derefed as a `*byte` from Go anyway.

File: proc/syscall_windows.go [hunk 4]
```diff
@@ -22,8 +22,53 @@ type _THREAD_BASIC_INFORMATION struct {
...
+type _EXIT_PROCESS_DEBUG_INFO struct {
+	ExitCode uint32
+}
+
+type _LOAD_DLL_DEBUG_INFO struct {
+	File                syscall.Handle
+	BaseOfDll           uintptr
+	DebugInfoFileOffset uint32
+	DebugInfoSize       uint32
+	ImageName           *byte
```
Comment (lukehoban) [inline proc/syscall_windows.go]: Same question as above.

File: proc/syscall_windows_amd64.go [hunk 5]
```diff
@@ -0,0 +1,95 @@
...
+	_CONTEXT_ALL                 = (_CONTEXT_CONTROL | _CONTEXT_INTEGER | _CONTEXT_SEGMENTS | _CONTEXT_FLOATING_POINT | _CONTEXT_DEBUG_REGISTERS)
+	_CONTEXT_EXCEPTION_ACTIVE    = 0x8000000
+	_CONTEXT_SERVICE_ACTIVE      = 0x10000000
+	_CONTEXT_EXCEPTION_REQUEST   = 0x40000000
+	_CONTEXT_EXCEPTION_REPORTING = 0x80000000
+)
+
+type _M128A struct {
+	low  uint64
+	high int64
```
Comment (lukehoban) [inline proc/syscall_windows_amd64.go]: Is it intentional to leave these lowercase?

**Comment by lukehoban** [comment]
This looks great.  

I had been looking at this in parallel, and your changes capture everything I had run across (including the `CONTEXT` alignment issue), but the syscall interfaces you have here are an even cleaner mapping that what I was using.

Other than the few review comments/questions, this looks good.

FWIW - This also fixes #412 and #416.

BTW - Build times on my laptop are halved with this change, and I can build on machines without MinGW (though of course have to avoid using the Makefile).  That's a really nice outcome.

File: proc/syscall_windows.go (hunk 1 above)
Comment (alexbrainman) [inline proc/syscall_windows.go]: This format is my personal preference. Russ likes to follow Go convention here - for example DEBUG_EVENT becomes DebugEvent (or debugEvent if you want identifier to be non-exported). I don't like Russ's approach because:
- sometimes it creates name clashes - win32 might have DebugEvent function or something, also DebugEvent is a good name for something in you code (also CONTEXT -> Context for example), so you end-up thinking of a different name, so you end up with some completely different name;
- you loose ability to Google for original name - once you have changed DEBUG_EVENT into DebugEvent, how do you search for struct definition on the Net?
So I prefer to keep Microsoft names as is. I also add leading _ to make name not exported. We don't want github.com/derekparker/proc users to be able to access / see these names.

File: proc/syscall_windows.go (hunk 2 above)
Comment (alexbrainman) [inline proc/syscall_windows.go]: Yes, you are correct. I have made mistake. Changed both to be uint32.

File: proc/syscall_windows.go (hunk 3 above)
Comment (alexbrainman) [inline proc/syscall_windows.go]: From the doco: "This parameter may be NULL, or it may contain the address of a string pointer in the address space of the process being debugged.", so maybe we can convert this into Go string (from ansii or utf16 depending on the fUnicode value). I don't see why you say that it is "in the address space of the debuggee". Where in the doco it says that? I think everything we see is in caller's address space.

File: proc/syscall_windows.go (hunk 4 above)
Comment (alexbrainman) [inline proc/syscall_windows.go]: Same answer as above.

File: proc/syscall_windows_amd64.go (hunk 5 above)
Comment (alexbrainman) [inline proc/syscall_windows_amd64.go]: No, it is a mistake. I have changed it to upper case.

**Comment by alexbrainman** [comment]
> FWIW - This also fixes #412 and #416.

Added these to my second commit. I have create #412 myself and then forgotten about it altogether.

> I can build on machines without MinGW 

Yes, like I said before.
```
go get github.com/derekparker/delve/cmd/dlv
```
is all you need to install dlv.exe on windows/amd64. Everywhere else (including linux, darwin and so on) it should be:
```
GOOS=windows GOARCH=amd64 go get github.com/derekparker/delve/cmd/dlv
```
Alex

**Comment by derekparker** [comment]
This LGTM. Can you please rebase and I will merge.

File: proc/syscall_windows.go (hunk 3 above)
Comment (lukehoban) [inline proc/syscall_windows.go]: This part of the doc you quoted is what I was referring to:

> in the address space of the process being debugged

So to read from this pointer requires a ReadProcessMemory call against the debuggee process.

That said - as described in http://www.codeproject.com/Articles/43682/Writing-a-basic-Windows-debugger this field is mostly not useful anyway. :-)

Comment (alexbrainman) [inline proc/syscall_windows.go]: I will take your word for it and change both "ImageName" into uintptr. Thanks for the article - my weekend reading.

**Comment by alexbrainman** [comment]
> Can you please rebase

How do I do that? I am git (and github) noob, so exact instructions are welcome. I tried and failed. Thank you.

Alex

**Comment by james-lawrence** [comment]
```bash
git rebase -i master
```
is the command to get you started. essentially it'll replay your commits on top of the later master having you resolve any conflicts. it can get kind of messy as the errors propagate up the commits.

**Comment by alexbrainman** [comment]
> git rebase -i master

I assume I should run this from my local convert_to_syscall branch. But that gives me some "merge errors" that I need to resolve manually. And that creates extra "merge" commit on top of my convert_to_syscall branch. What should I do with the extra branch? Should I combine it all into one new branch?

Thank you.

Alex

**Comment by james-lawrence** [comment]
eh? no extra branch should be created. want to clarify what you mean?

you should see a screen like this pop up:
```text
pick 3245ad 'commit 1'
pick 34def63 'commit 2'
```
this is just allowing you to specify what you want to do with the commits you are rebasing. (you can combine commits, which is called squashing, delete commits, etc) for what you're trying to do leave them all as picks.

**Comment by alexbrainman** [comment]
> eh? no extra branch should be created. want to clarify what you mean?

I run `git rebase -i master` and that worked (I had to resolve some conflicts along the way, but it worked). Now I want to send my local convert_to_syscall branch changes onto my github fork of delve. This is what I tried:
```
$ git status
On branch convert_to_syscall
Your branch and 'origin/convert_to_syscall' have diverged,
and have 7 and 2 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

nothing to commit, working directory clean
$ git push origin convert_to_syscall
To git@github.com:alexbrainman/delve.git
 ! [rejected]        convert_to_syscall -> convert_to_syscall (non-fast-forward)
error: failed to push some refs to 'git@github.com:alexbrainman/delve.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
$
```

I am not sure what to do now.

Alex

**Comment by lukehoban** [comment]
You can `git push -f origin convert_to_syscall` to overwrite the commits in the PR branch with the new commit that you created after the rebase.  See for example: http://stackoverflow.com/a/24527934

**Comment by alexbrainman** [comment]
> `git push -f origin convert_to_syscall`

That does the trick. Thank you. I still need to change ImageName.

Alex

**Comment by alexbrainman** [comment]
Now I am done. Thanks for you help @james-lawrence and @lukehoban.

Alex

**Comment by lukehoban** [comment]
@alexbrainman I expect @derekparker will want the commits to be squashed.  You can do `git rebase -i origin/master` and then set the first commit to `pick` and the latter two commits to `squash`.  This will result in a single commit off of master with all of your work on this.

**Comment by lukehoban** [comment]
BTW - I can't tell why you are seeing test failures on OSX and Linux on Go1.6 here.  As far as I can tell - there are no changes in this PR that are even part of the build on those platforms.

**Comment by alexbrainman** [comment]
> You can do git rebase -i origin/master and 

Done.

> I can't tell why you are seeing test failures on OSX and Linux on Go1.6 here

I will let Derek decide what to do here.

Alex

**Comment by aarzilli** [comment]
Delve on OS X has a race condition on `Launch` that's hard to fix (because lack of documentation), that's why sometimes tests fail on OS X. 
@alexbrainman: if you are interested in understanding git, for me the best introduction was [Git from the Bottom Up](https://jwiegley.github.io/git-from-the-bottom-up/).

**Comment by alexbrainman** [comment]
@aarzilli I know enough git to be dangerous. So I prefer to ask, when I am not sure.

Alex

**Comment by derekparker** [comment]
Thank you @alexbrainman for your help on this!

**Comment by derekparker** [comment]
@lukehoban now that this is merged, the build instructions can be simplified on Windows, correct? Would you mind updating the wiki with the correct instructions please.

**Comment by alexbrainman** [comment]
@derekparker and @lukehoban ping me if you need any help with windows code in the future.

Alex

**Comment by joegrasse** [comment]
@lukehoban  or @derekparker , just wanted to confirm, so with this change do you no longer need to use MinGW on windows to install delve?

**Comment by lukehoban** [comment]
@joegrasse That's right - you no longer need MinGW to build and use Delve on Windows.  For doing development work on Delve though, folks may want to use the Makefile, and for that you'll need a make install (and a few other tools used by the Makefile).  Technically though, you don't need to use the Makefile to build.
