### PR TITLE
proc: support for ver. 10.12.1 the OS formerly known as Mac OS X

### LINKED ISSUE #645: OS X: cannot get thread count
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.
1. What version of Delve are you using (`dlv version`)?
   Delve Debugger
   Version: 0.11.0-alpha
   Build: fb8388ab2e50ca28ef9a83c73c329f8d0b6234d9
2. What version of Go are you using? (`go version`)?
   go version go1.7.1 darwin/amd64
3. What operating system and processor architecture are you using?
   OS X 10.12.1 Beta (16B2333a) (developer beta 2 Sept 28)
4. What did you do?
   Tried to debug my app from within Visual Studio Code and from the command line with the same results
5. What did you expect to see?
   Debugging goodness
6. What did you see instead?
   From VS Code:
   2016/09/29 06:26:35 server.go:71: Using API v1
   2016/09/29 06:26:35 debugger.go:61: launching process with args: [./debug -race -tags debug]
   could not launch process: could not get thread count
   
   From terminal:
   joefrancia@iMac [6:17:20]: dlv debug
   could not launch process: could not get thread count

I believe it may be related to the upgrade from Sierra beta 1 to beta 2. I was debuggin a'plenty earlier in the afternoon on my MacBook which was still on beta 1, but when I tried on the iMac I got the above failure. The iMac is beta 2. I've since upgraded the MacBook to beta 2 (this was before I realized there may be a problem) and now I get the same error on the MacBook.

### PR DESCRIPTION
**Pull request by aarzilli**
Fixes #645

Works on minimal example, makes delve slower, not tested on versions of OS X before 10.12.1, not tested on 10.12.2, needs printf cleanup, needs gofmt.

If someone wants to finish this instead of me I want nothing more than wash my hands of the undocumented mess that is Mac OS X, OS X or macOS is.

### CODE REVIEW

**Comment by brenreid** [comment]
thanks for the effort @aarzilli 

macOS Sierra 10.12.1
go version 1.7.3

I [checked out the PR locally](https://gist.github.com/piscisaureus/3342247) 
`git checkout pr/665` 
and then followed the OS X manual install steps.

On trying 
`dlv debug myprog.goI`
 I get the same error 
`could not launch process: could not get thread count`
 as previously.
A reboot didn't help

**Comment by peterhagelund** [comment]
Did a local build of pr/665 on 10.12.1 and things work, but are a tad slow - 2-3 seconds for a step on a high-end MBP.  Thanks for figuring this out!

**Comment by derekparker** [comment]
@aarzilli thanks for the patch.

> If someone wants to finish this instead of me I want nothing more than wash my hands of the undocumented mess that is Mac OS X, OS X or macOS is.

:joy: I know that pain all too well.

I'll take a look at this, should actually have some time today.

**Comment by aarzilli** [comment]
proc test set passing fully with the exception of cgo tests (`golang.org/x/debug/dwarf` seems to have trouble parsing DWARF info output by the new macOS ld, further investigation needed)

File: proc/proc_darwin.c [hunk 1]
```diff
@@ -68,6 +70,29 @@ acquire_mach_task(int tid,
...
+kern_return_t
+reacquire_mach_task(task_t task, mach_port_t *exception_port, mach_port_t *notification_port) {
+	kern_return_t kret;
+	mach_port_t prev_not;
+	mach_port_t self = mach_task_self();
+	
+	kret = task_set_exception_ports(task, EXC_MASK_BREAKPOINT|EXC_MASK_SOFTWARE, *exception_port,
+			EXCEPTION_DEFAULT, THREAD_STATE_NONE);
+	if (kret != KERN_SUCCESS) {
+		printf("task_set_exception_ports: %d\n", kret);
```
Comment (derekparker) [inline proc/proc_darwin.c]: nit: If you plan on keeping this logging (probably not a bad idea), I'd say something more along the lines of:

("error during reaquire_mach_task: could not set exception ports: %s", mach_error_string(kret))

File: proc/proc_darwin.c [hunk 2]
```diff
@@ -68,6 +70,29 @@ acquire_mach_task(int tid,
...
+		return kret;
+	}
+	
+	kret = mach_port_request_notification(self, task, MACH_NOTIFY_DEAD_NAME, 0, *notification_port,
+			MACH_MSG_TYPE_MAKE_SEND_ONCE, &prev_not);
+	if (kret != KERN_SUCCESS) {
+		printf("mach_port_request_notification: %d\n", kret);
```
Comment (derekparker) [inline proc/proc_darwin.c]: Same nit as above, better error logging here.

File: proc/proc_darwin.c [hunk 3]
```diff
@@ -76,10 +101,15 @@ find_executable(int pid) {
...
 kern_return_t
-get_threads(task_t task, void *slice, int limit) {
+get_threads(int pid, void *slice, int limit) {
 	kern_return_t kret;
 	thread_act_array_t list;
 	mach_msg_type_number_t count;
+	mach_port_t self = mach_task_self();
+	task_t task;
+
+	kret = task_for_pid(self, pid, &task);
```
Comment (derekparker) [inline proc/proc_darwin.c]: Calling `task_for_pid` is likely going to be pretty inefficient. Since we now know the error lies with OSX changes tasks underneath us during exec, can we just use the task we've reaquired?

File: proc/proc_darwin.c [hunk 4]
```diff
@@ -100,10 +130,15 @@ get_threads(task_t task, void *slice, int limit) {
...
 int
-thread_count(task_t task) {
+thread_count(int pid) {
 	kern_return_t kret;
 	thread_act_array_t list;
 	mach_msg_type_number_t count;
+	mach_port_t self = mach_task_self();
+	task_t task;
+
+	kret = task_for_pid(self, pid, &task);
```
Comment (derekparker) [inline proc/proc_darwin.c]: Calling `task_for_pid` is likely going to be pretty inefficient. Since we now know the error lies with OSX changes tasks underneath us during exec, can we just use the task we've reaquired?

File: proc/proc_darwin.go [hunk 5]
```diff
@@ -316,6 +362,18 @@ func (dbp *Process) trapWait(pid int) (*Thread, error) {
 		case 0:
 			return nil, fmt.Errorf("error while waiting for task")
 		}
+		
+		// In macOS 10.12.1 if we received a notification for a task other than
+		// the inferior's task and the inferior's task is no longer valid, this
+		// means inferior called execve and its task_t changed.
+		if dbp.os.task != task && C.task_is_valid(dbp.os.task) == 0 {
+			fmt.Printf("task %d -> %d\n", dbp.os.task, task)
```
Comment (derekparker) [inline proc/proc_darwin.go]: nit: remove this print lines, or use proper logging which we can enable / disable via log flag.

File: proc/proc_darwin.go [hunk 6]
```diff
@@ -292,11 +323,26 @@ func (dbp *Process) findExecutable(path string) (*macho.File, error) {
...
+		port := C.mach_port_wait(dbp.os.portSet, &task, C.int(0))
 
 		switch port {
 		case dbp.os.notificationPort:
+			// on macOS >= 10.12.1 the task_t changes after an execve, we could
+			// receive the notification for the death of the pre-execve task_t,
+			// this could also happen *before* we are notified that our task_t has
+			// changed.
+			if dbp.os.task != task {
+				fmt.Printf("ignoring death of %d (%d)\n", task, dbp.os.task)
```
Comment (derekparker) [inline proc/proc_darwin.go]: nit: remove this print lines, or use proper logging which we can enable / disable via log flag.

File: proc/proc_darwin.go [hunk 7]
```diff
@@ -292,11 +323,26 @@ func (dbp *Process) findExecutable(path string) (*macho.File, error) {
...
+				continue trapWaitLoop
+			}
+			if pidtask := C.get_task_for_pid(C.int(dbp.Pid)); pidtask != 0 && dbp.os.task != pidtask {
+				fmt.Printf("ignoring death of %d (%d) - 2\n", pidtask, dbp.os.task)
```
Comment (derekparker) [inline proc/proc_darwin.go]: nit: remove this print lines, or use proper logging which we can enable / disable via log flag.

File: proc/proc_darwin.go [hunk 8]
```diff
@@ -292,11 +323,26 @@ func (dbp *Process) findExecutable(path string) (*macho.File, error) {
...
+				continue trapWaitLoop
+			}
+			fmt.Printf("death of %d\n", dbp.os.task)
```
Comment (derekparker) [inline proc/proc_darwin.go]: nit: remove this print lines, or use proper logging which we can enable / disable via log flag.

File: proc/variables.go [hunk 9]
```diff
@@ -163,7 +163,7 @@ func newVariable(name string, addr uintptr, dwarfType dwarf.Type, dbp *Process,
 	}
 
 	v.RealType = resolveTypedef(v.DwarfType)
-
+
```
Comment (derekparker) [inline proc/variables.go]: nit: Get rid of whitespace.

File: proc/proc_test.go [hunk 10]
```diff
@@ -676,6 +676,11 @@ func TestCGONext(t *testing.T) {
 	if runtime.GOOS == "darwin" && strings.Contains(runtime.Version(), "1.4") {
 		return
 	}
+	
+	if runtime.GOOS == "darwin" {
+		//XXX- temporarily disabled due to inability to read DWARF info on macOS >= 10.12.1
```
Comment (derekparker) [inline proc/proc_test.go]: I won't block on merging because of this, but let's create an issue so we can do a follow up PR.

**Comment by aarzilli** [comment]
Update: still fails randomly on macOS 10.12.1, sometimes in ways that don't make much sense (for example getting blocked forever in a call to mach_msg that has a timeout set). I still haven't looked into cgo support.

**Comment by aarzilli** [comment]
Do we know which version of macOS travis is running?

**Comment by zchee** [comment]
@aarzilli If not set `osx_image`, will using `OS X 10.11` by default.
https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version

If want to test with 10.12 Sierra, need
```yml
# uname -a: Darwin Traviss-Mac.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
osx_image: xcode8.1

# uname -a: Darwin Traviss-Mac.local 16.1.0 Darwin Kernel Version 16.1.0: Thu Oct 13 21:26:57 PDT 2016; root:xnu-3789.21.3~60/RELEASE_X86_64 x86_64
osx_image: xcode8.2
```

But note that currently, travis-ci tip build have Sierra ABI issue because of use go1.6 for `$GOROOT_BOOTSTRAP`. So will fail `tip` build on `gimme` setup.
https://twitter.com/_zchee_/status/799268285082517505
https://travis-ci.org/ko1s/ci-test/jobs/176712707

**Comment by thalesfsp** [comment]
When it will get merged?

**Comment by derekparker** [comment]
@thalesfsp will be merged this week, going to do another full review today, and get this merged in as quickly as we can, sorry for the delay, it's been a busy few weeks.

File: proc/proc_darwin.go [hunk 11]
```diff
@@ -292,11 +352,25 @@ func (dbp *Process) findExecutable(path string) (*macho.File, error) {
 }
 
 func (dbp *Process) trapWait(pid int) (*Thread, error) {
+trapWaitLoop:
```
Comment (derekparker) [inline proc/proc_darwin.go]: You don't need this label, the `continue` statements within the `switch` will operate on the `for` loop.

File: proc/proc_darwin.go [hunk 12]
```diff
@@ -81,11 +82,48 @@ func Launch(cmd []string, wd string) (*Process, error) {
 		C.free(unsafe.Pointer(argvSlice[i]))
 	}
 
+	for {
```
Comment (derekparker) [inline proc/proc_darwin.go]: nit: Could you add some more comments to these new lines, just explaining what's happening during intitialization. It's a tricky process, so we should be describing it well.

File: proc/exec_darwin.c [hunk 13]
```diff
@@ -97,6 +97,8 @@ fork_exec(char *argv0, char **argv, int size,
 		exit(1);
 	}
 
+	sleep(1);
```
Comment (aarzilli) [inline proc/exec_darwin.c]: lldb does it but provides no explanation. I suspect it is just to avoid introducing race conditions accidentally, rather than circumventing one, but I don't know.
