### PR TITLE
terminal,service: auto-continue during next and step

### LINKED ISSUE #387: proc: next while nexting
Running into an issue, testing out 'next'ing with multiple goroutines, and eventually I end up on the wrong goroutine, and when I try and 'next' again, I get the error: 'next while nexting'.

I have been able to repro on my OSX machine and a Linux VM.

Example code: 

```go

func dostuff(id int, wg *sync.WaitGroup) {
	fmt.Println("goroutine:", id)
	fmt.Println("goroutine:", id)
	wg.Done()
}

func main() {
	runtime.Breakpoint()

	var wg sync.WaitGroup
	wg.Add(10)
	for i := 0; i < 10; i++ {
		go dostuff(i, &wg)
	}
	wg.Wait()
}
```

Set a breakpoint on `dostuff` and then print id, next, print id, next and usually the third time it happens.

cc: @aarzilli - might not have time to track this down until later, but we need to get this fixed :).

### PR DESCRIPTION
**Pull request by aarzilli**
Make dlv call continue automatically when a breakpoint is hit on a
different goroutine during a next or step operation.
Added API hooks to implement the other solution to this problem (cancel
the next/step operation if a different breakpoint is hit).

Fixes #387

### CODE REVIEW

**Comment by aarzilli** [comment]
looks like there's a bug

**Comment by aarzilli** [comment]
fixed it

**Comment by derekparker** [comment]
I'll be taking a closer look and testing this out either today or tomorrow. Sorry for the delay.

**Comment by aarzilli** [comment]
rebased.

File: service/debugger/debugger.go [hunk 1]
```diff
@@ -163,6 +163,12 @@ func (d *Debugger) state() (*api.DebuggerState, error) {
 		}
 	}
 
+	for _, bp := range d.process.Breakpoints {
+		if bp.Temp {
+			state.NextInProgress = true
```
Comment (derekparker) [inline service/debugger/debugger.go]: Break loop when this condition is met.

File: service/debugger/debugger.go [hunk 2]
```diff
@@ -243,6 +249,10 @@ func (d *Debugger) AmendBreakpoint(amend *api.Breakpoint) error {
 	return copyBreakpointInfo(original, amend)
 }
 
+func (d *Debugger) CancelNext() {
+	d.process.ClearTempBreakpoints()
```
Comment (derekparker) [inline service/debugger/debugger.go]: Propagate error here.

File: terminal/command.go [hunk 3]
```diff
@@ -443,13 +443,35 @@ func cont(t *Term, ctx callContext, args string) error {
...
+		stateChan := t.client.Continue()
+		var state *api.DebuggerState
+		for state = range stateChan {
+			if state.Err != nil {
+				return state.Err
+			}
+			printcontext(t, state)
+		}
+		if state.NextInProgress {
+			fmt.Printf("\tbreakpoint hit during %s, continuing...\n", op)
```
Comment (derekparker) [inline terminal/command.go]: Could be nice to give some details on the breakpoint that we're skipping.

File: terminal/command.go [hunk 4]
```diff
@@ -443,13 +443,35 @@ func cont(t *Term, ctx callContext, args string) error {
...
+	for {
+		stateChan := t.client.Continue()
+		var state *api.DebuggerState
+		for state = range stateChan {
+			if state.Err != nil {
+				return state.Err
+			}
+			printcontext(t, state)
+		}
+		if state.NextInProgress {
```
Comment (derekparker) [inline terminal/command.go]: nit: maybe refactor to:

```go
if !state.NextInProgress {
        break
}
fmt.Printf("...")
```

File: terminal/command.go [hunk 5]
```diff
@@ -443,13 +443,35 @@ func cont(t *Term, ctx callContext, args string) error {
...
+}
+
 func step(t *Term, ctx callContext, args string) error {
 	state, err := t.client.Step()
 	if err != nil {
 		return err
 	}
 	printcontext(t, state)
-	return nil
+	if !state.NextInProgress {
```
Comment (derekparker) [inline terminal/command.go]: nit: would also recommend refactor to:

```go
if state.NextInProgress {
        return continueUntilCompleteNext(t, "step")
}
return nil
```

File: terminal/command.go [hunk 6]
```diff
@@ -467,7 +489,10 @@ func next(t *Term, ctx callContext, args string) error {
...
```
Comment (derekparker) [inline terminal/command.go]: Same refactor nit here.

**Comment by derekparker** [comment]
I like giving an option to the caller of whether they want to acknowledge the breakpoint or not.

File: terminal/command.go (hunk 3 above)
Comment (aarzilli) [inline terminal/command.go]: The call to `printcontext(t, state)` will do that.

**Comment by aarzilli** [comment]
I should have addressed everything.

**Comment by aarzilli** [comment]
Rebased, moved `CancelNext` to rpc2 exclusively.

**Comment by derekparker** [comment]
Needs rebase.

**Comment by aarzilli** [comment]
Rebased.
