### PR TITLE
Replaced net/rpc with custom version

### LINKED ISSUE #523: service/rpc: RPC server should serve requests consequently
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? 82ece54

2. What version of Go are you using? (`go version`)? 1.6.2

3. What operating system and processor architecture are you using? osx/windows

4. What did you do? use rpc protocol for debugging

5. What did you expect to see? consequently invoked procedures

6. What did you see instead? createBreakpoint and continue methods are reordered randomly

[rpc.ServeCodec](https://github.com/derekparker/delve/blob/master/service/rpc1/server.go#L94) runs all remote methods via go-routine. So it cannot give any guarantees about methods invokation order. As a result we have following bugs in IDEA<->Delve integration when breakpoints are set after continue command invokation: go-lang-plugin-org/go-lang-idea-plugin#2360

I've suggested the https://github.com/derekparker/delve/pull/520 which uses ServeRequest method instead, which is synchronously approach of serving request. It fixes the problem but unfortunately it's not a proper implementation because it breaks halting the process.

### PR DESCRIPTION
**Pull request by aarzilli**
This version preserves the order of requests, allows the
client to switch between API versions and introduces a
way to send notifications to the client (see TODO item at:
proc/proc_linux.go:325).

Fixes #523, #571

### CODE REVIEW

**Comment by derekparker** [comment]
I will take a look today, was on vacation all last week.

File: service/rpc2/client.go [hunk 1]
```diff
@@ -26,10 +26,9 @@ func NewClient(addr string) *RPCClient {
 	if err != nil {
 		log.Fatal("dialing:", err)
 	}
-	return &RPCClient{
-		addr:   addr,
-		client: client,
-	}
+	c := &RPCClient{ addr:   addr, client: client }
```
Comment (derekparker) [inline service/rpc2/client.go]: Needs gofmt.

File: service/rpc2/server.go [hunk 2]
```diff
@@ -3,101 +3,21 @@ package rpc2
...
-
 type RPCServer struct {
 	// config is all the information necessary to start the debugger and server.
 	config *service.Config
-	// listener is used to serve HTTP.
-	listener net.Listener
-	// stopChan is used to stop the listener goroutine
-	stopChan chan struct{}
-	// debugger is a debugger service.
+	// debugger is a debugger service
```
Comment (derekparker) [inline service/rpc2/server.go]: Preserve punctuation.

File: service/rpccommon/server.go [hunk 3]
```diff
@@ -0,0 +1,342 @@
...
+	"github.com/derekparker/delve/service/rpc2"
+	"github.com/derekparker/delve/version"
+)
+
+type ServerImpl struct {
+	// config is all the information necessary to start the debugger and server.
+	config *service.Config
+	// listener is used to serve HTTP.
+	listener net.Listener
+	// stopChan is used to stop the listener goroutine
```
Comment (derekparker) [inline service/rpccommon/server.go]: nit: Add punctuation to end of comments.

File: service/rpccommon/server.go [hunk 4]
```diff
@@ -0,0 +1,342 @@
...
+// NewServer creates a new RPCServer.
+func NewServer(config *service.Config, logEnabled bool) *ServerImpl {
+	log.SetFlags(log.Ldate | log.Ltime | log.Lshortfile)
+	if !logEnabled {
+		log.SetOutput(ioutil.Discard)
+	}
+	if config.ApiVersion < 2 {
+		log.Printf("Using API v1")
+	}
+
```
Comment (derekparker) [inline service/rpccommon/server.go]: nit: remove white space.

File: service/rpccommon/server.go [hunk 5]
```diff
@@ -0,0 +1,342 @@
...
+		stopChan: make(chan struct{}),
+	}
+}
+
+func (s *ServerImpl) Stop(kill bool) error {
+	if s.config.AcceptMulti {
+		close(s.stopChan)
+		s.listener.Close()
+	}
+	err := s.debugger.Detach(kill)
```
Comment (derekparker) [inline service/rpccommon/server.go]: nit: return error directly.

File: service/rpccommon/server.go [hunk 6]
```diff
@@ -0,0 +1,342 @@
...
+func isExportedOrBuiltinType(t reflect.Type) bool {
+	for t.Kind() == reflect.Ptr {
+		t = t.Elem()
+	}
+	// PkgPath will be non-empty even for an exported type,
+	// so we need to check the type name as well.
+	return isExported(t.Name()) || t.PkgPath() == ""
+}
+
+func suitableMethods(rcvr interface{}, methods map[string]*methodType) {
```
Comment (derekparker) [inline service/rpccommon/server.go]: Needs doc.

File: service/rpccommon/server.go [hunk 7]
```diff
@@ -0,0 +1,342 @@
...
+		resp.Error = errmsg
+		reply = invalidRequest
+	}
+	resp.Seq = req.Seq
+	sending.Lock()
+	err := codec.WriteResponse(resp, reply)
+	if err != nil {
+		log.Println("rpc: writing response:", err)
+	}
+	sending.Unlock()
```
Comment (derekparker) [inline service/rpccommon/server.go]: Unlock in a defer after acquiring lock.

**Comment by aarzilli** [comment]
Updated 

cc @zolotov, @dlsniper, @ignatov: does this fix the problem on your side?

**Comment by dlsniper** [comment]
@aarzilli will check in a few minutes, thank you!

**Comment by dlsniper** [comment]
@aarzilli well not exactly a few minutes, but 10 / 10 it worked so far. Thank you so much for your efforts on this!

**Comment by dlsniper** [comment]
Hmm, I've ran just `make` and I've got this:

```
go test  -ldflags="-X main.Build=f6f7919d0108e4b979319a518f370ec44f8ec04b" github.com/derekparker/delve/cmd/dlv github.com/derekparker/delve/cmd/dlv/cmds github.com/derekparker/delve/config github.com/derekparker/delve/dwarf/debug/dwarf github.com/derekparker/delve/dwarf/debug/elf github.com/derekparker/delve/dwarf/debug/macho github.com/derekparker/delve/dwarf/frame github.com/derekparker/delve/dwarf/line github.com/derekparker/delve/dwarf/op github.com/derekparker/delve/dwarf/reader github.com/derekparker/delve/dwarf/util github.com/derekparker/delve/proc github.com/derekparker/delve/proc/test github.com/derekparker/delve/service github.com/derekparker/delve/service/api github.com/derekparker/delve/service/debugger github.com/derekparker/delve/service/rpc1 github.com/derekparker/delve/service/rpc2 github.com/derekparker/delve/service/rpccommon github.com/derekparker/delve/service/test github.com/derekparker/delve/service/test/cmd github.com/derekparker/delve/terminal github.com/derekparker/delve/version
?       github.com/derekparker/delve/cmd/dlv    [no test files]
?       github.com/derekparker/delve/cmd/dlv/cmds       [no test files]
?       github.com/derekparker/delve/config     [no test files]
?       github.com/derekparker/delve/dwarf/debug/dwarf  [no test files]
?       github.com/derekparker/delve/dwarf/debug/elf    [no test files]
?       github.com/derekparker/delve/dwarf/debug/macho  [no test files]
ok      github.com/derekparker/delve/dwarf/frame        0.003s
ok      github.com/derekparker/delve/dwarf/line 0.183s
ok      github.com/derekparker/delve/dwarf/op   0.002s
?       github.com/derekparker/delve/dwarf/reader       [no test files]
ok      github.com/derekparker/delve/dwarf/util 0.001s


Hello, World!
Hello, World!
past main
foo
--- FAIL: TestNextGeneral (0.96s)
        proc_test.go:327: Program did not continue to correct next location expected 34 was testnextprog.go:28
hi 9
hi 3
hi 3
hi 6
hi 6
hi 8
hi 8
hi 2
hi 2
hi 5
hi 5
hi 0
hi 0
hi 9
hi 0
hi 0
hi 7
hi 4
hi 1
hi 7
hi 1
hi 4
hi 6
hi 6
hi 8
hi 2
hi 9
hi 5
hi 8
hi 3
hi 3
hi 9
hi 2
foo
Hello, World!
bye
hi
hi
hi
hi
Tue Jun 21 22:18:22 BST 2016
default
id: 1 step: 0 sleeping 2
id: 2 step: 0 sleeping 8
id: 1 step: 1 sleeping 10
id: 2 step: 1 sleeping 8
id: 2 step: 2 sleeping 2
id: 1 step: 2 sleeping 9
id: 2 step: 3 sleeping 6
id: 2 step: 4 sleeping 1
id: 1 step: 3 sleeping 7
id: 2 step: 5 sleeping 1
id: 1 step: 4 sleeping 5
id: 2 step: 6 sleeping 2
id: 1 step: 5 sleeping 3
id: 2 step: 7 sleeping 10
id: 1 step: 6 sleeping 9
id: 1 step: 7 sleeping 5
id: 2 step: 8 sleeping 2
id: 1 step: 8 sleeping 6
id: 2 step: 9 sleeping 8
id: 2 step: 10 sleeping 7
id: 1 step: 9 sleeping 6
id: 1 step: 10 sleeping 7
id: 2 step: 11 sleeping 9
id: 1 step: 11 sleeping 9
id: 2 step: 12 sleeping 8
id: 1 step: 12 sleeping 8
id: 1 step: 13 sleeping 8
id: 2 step: 13 sleeping 9
id: 2 step: 14 sleeping 1
id: 1 step: 14 sleeping 6
id: 1 step: 15 sleeping 2
id: 2 step: 15 sleeping 9
id: 1 step: 16 sleeping 8
id: 1 step: 17 sleeping 2
id: 2 step: 16 sleeping 10
id: 1 step: 18 sleeping 7
id: 1 step: 19 sleeping 8
id: 2 step: 17 sleeping 2
id: 2 step: 18 sleeping 6
id: 1 step: 20 sleeping 7
id: 1 step: 21 sleeping 4
id: 2 step: 19 sleeping 1
id: 2 step: 20 sleeping 5
id: 1 step: 22 sleeping 4
id: 1 step: 23 sleeping 4
id: 2 step: 21 sleeping 8
id: 1 step: 24 sleeping 9
id: 2 step: 22 sleeping 5
id: 1 step: 25 sleeping 10
id: 2 step: 23 sleeping 4
id: 1 step: 26 sleeping 8
id: 2 step: 24 sleeping 2
id: 2 step: 25 sleeping 10
id: 2 step: 26 sleeping 10
id: 1 step: 27 sleeping 1
id: 2 step: 27 sleeping 6
id: 1 step: 28 sleeping 9
id: 1 step: 29 sleeping 9
id: 2 step: 28 sleeping 4
id: 1 step: 30 sleeping 6
id: 2 step: 29 sleeping 2
id: 2 step: 30 sleeping 1
id: 2 step: 31 sleeping 6
id: 1 step: 31 sleeping 7
id: 2 step: 32 sleeping 7
id: 1 step: 32 sleeping 9
id: 1 step: 33 sleeping 2
id: 2 step: 33 sleeping 3
id: 1 step: 34 sleeping 4
id: 2 step: 34 sleeping 7
id: 1 step: 35 sleeping 4
id: 2 step: 35 sleeping 7
id: 2 step: 36 sleeping 3
id: 1 step: 36 sleeping 9
id: 2 step: 37 sleeping 8
id: 1 step: 37 sleeping 5
id: 2 step: 38 sleeping 8
id: 1 step: 38 sleeping 4
id: 2 step: 39 sleeping 7
id: 1 step: 39 sleeping 1
id: 1 step: 40 sleeping 4
id: 1 step: 41 sleeping 4
id: 2 step: 40 sleeping 8
id: 1 step: 42 sleeping 4
id: 2 step: 41 sleeping 2
id: 1 step: 43 sleeping 10
id: 2 step: 42 sleeping 4
id: 1 step: 44 sleeping 4
id: 2 step: 43 sleeping 2
id: 2 step: 44 sleeping 3
id: 2 step: 45 sleeping 9
id: 1 step: 45 sleeping 7
id: 1 step: 46 sleeping 7
id: 1 step: 47 sleeping 8
id: 2 step: 46 sleeping 1
id: 1 step: 48 sleeping 4
id: 2 step: 47 sleeping 3
id: 2 step: 48 sleeping 4
id: 1 step: 49 sleeping 6
id: 2 step: 49 sleeping 9
id: 1 step: 50 sleeping 6
id: 2 step: 50 sleeping 2
id: 1 step: 51 sleeping 6
id: 2 step: 51 sleeping 8
id: 1 step: 52 sleeping 8
id: 2 step: 52 sleeping 1
id: 1 step: 53 sleeping 1
id: 2 step: 53 sleeping 1
id: 1 step: 54 sleeping 6
id: 2 step: 54 sleeping 3
id: 1 step: 55 sleeping 9
id: 2 step: 55 sleeping 4
id: 1 step: 56 sleeping 2
id: 2 step: 56 sleeping 3
id: 2 step: 57 sleeping 5
id: 1 step: 57 sleeping 8
id: 2 step: 58 sleeping 8
id: 1 step: 58 sleeping 8
id: 2 step: 59 sleeping 2
id: 2 step: 60 sleeping 5
id: 1 step: 59 sleeping 7
id: 2 step: 61 sleeping 3
id: 1 step: 60 sleeping 2
id: 2 step: 62 sleeping 10
id: 2 step: 63 sleeping 7
id: 1 step: 61 sleeping 1
id: 1 step: 62 sleeping 4
id: 1 step: 63 sleeping 10
id: 2 step: 64 sleeping 7
id: 1 step: 64 sleeping 2
id: 2 step: 65 sleeping 3
id: 2 step: 66 sleeping 6
id: 1 step: 65 sleeping 6
id: 2 step: 67 sleeping 1
id: 1 step: 66 sleeping 8
id: 1 step: 67 sleeping 10
id: 2 step: 68 sleeping 9
id: 2 step: 69 sleeping 9
id: 1 step: 68 sleeping 5
id: 2 step: 70 sleeping 4
id: 1 step: 69 sleeping 5
id: 2 step: 71 sleeping 8
id: 1 step: 70 sleeping 3
id: 1 step: 71 sleeping 3
id: 2 step: 72 sleeping 7
id: 2 step: 73 sleeping 10
id: 1 step: 72 sleeping 1
id: 2 step: 74 sleeping 7
id: 1 step: 73 sleeping 2
id: 1 step: 74 sleeping 7
id: 2 step: 75 sleeping 1
id: 1 step: 75 sleeping 2
id: 2 step: 76 sleeping 5
id: 1 step: 76 sleeping 5
id: 2 step: 77 sleeping 6
id: 2 step: 78 sleeping 4
id: 1 step: 77 sleeping 2
id: 2 step: 79 sleeping 1
id: 1 step: 78 sleeping 3
id: 2 step: 80 sleeping 9
id: 1 step: 79 sleeping 8
id: 2 step: 81 sleeping 2
id: 1 step: 80 sleeping 9
id: 2 step: 82 sleeping 5
id: 1 step: 81 sleeping 3
id: 2 step: 83 sleeping 4
id: 2 step: 84 sleeping 3
id: 1 step: 82 sleeping 9
id: 1 step: 83 sleeping 9
id: 2 step: 85 sleeping 4
id: 2 step: 86 sleeping 7
id: 1 step: 84 sleeping 1
id: 2 step: 87 sleeping 6
id: 2 step: 88 sleeping 1
id: 1 step: 85 sleeping 5
id: 2 step: 89 sleeping 3
id: 2 step: 90 sleeping 8
id: 1 step: 86 sleeping 6
id: 1 step: 87 sleeping 2
id: 2 step: 91 sleeping 10
id: 1 step: 88 sleeping 1
id: 1 step: 89 sleeping 4
id: 2 step: 92 sleeping 1
id: 2 step: 93 sleeping 10
id: 1 step: 90 sleeping 1
id: 2 step: 94 sleeping 4
id: 1 step: 91 sleeping 1
id: 2 step: 95 sleeping 5
id: 1 step: 92 sleeping 8
id: 2 step: 96 sleeping 1
id: 1 step: 93 sleeping 6
id: 2 step: 97 sleeping 3
id: 1 step: 94 sleeping 10
id: 2 step: 98 sleeping 1
id: 2 step: 99 sleeping 9
id: 1 step: 95 sleeping 7
id: 1 step: 96 sleeping 6
id: 1 step: 97 sleeping 7
id: 1 step: 98 sleeping 1
id: 1 step: 99 sleeping 7
2
0
1
2
hi 3
hi 3
hi 9
hi 9
hi 6
hi 6
hi 0
hi 0
hi 3
hi 3
hi 0
hi 0
hi 6
hi 6
hi 9
hi 9
[]
[Todd]
[]
[Todd]
[Todd]
received args []string{"/tmp/testargs.883d2e0b", "test"}
received args []string{"/tmp/testargs.883d2e0b", "test", "pass flag"}
received args []string{"/tmp/testargs.883d2e0b", "test pass", "flag"}
received args []string{"/tmp/testargs.883d2e0b", "test", "pass", "flag"}
received args []string{"/tmp/testargs.883d2e0b", "test pass flag"}
received args []string{"/tmp/testargs.883d2e0b"}
received args []string{"/tmp/testargs.883d2e0b", "invalid"}
received args []string{"/tmp/testargs.883d2e0b", "test", "invalid"}
received args []string{"/tmp/testargs.883d2e0b", "invalid", "pass flag"}
Start
Receive signal interrupt 
End
FAIL
FAIL    github.com/derekparker/delve/proc       52.072s
?       github.com/derekparker/delve/proc/test  [no test files]
?       github.com/derekparker/delve/service    [no test files]
?       github.com/derekparker/delve/service/api        [no test files]
?       github.com/derekparker/delve/service/debugger   [no test files]
?       github.com/derekparker/delve/service/rpc1       [no test files]
?       github.com/derekparker/delve/service/rpc2       [no test files]
?       github.com/derekparker/delve/service/rpccommon  [no test files]
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
foo
--- FAIL: Test1NextGeneral (0.55s)
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:17, end:19}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:19, end:20}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:20, end:23}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:23, end:24}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:24, end:26}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:26, end:31}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:31, end:23}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:23, end:24}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:24, end:26}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:26, end:31}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:31, end:23}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:23, end:24}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:24, end:26}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:26, end:27}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:27, end:34}
        integration1_test.go:222: Program did not continue to correct next location expected 34 was 28
foo
Hello, World!
foo
Hello, World!
hi
hi
hi
hi
hi
hi
Hello, World!
hi 9
hi 9
hi 6
hi 6
hi 3
hi 3
Start
Node: domains
        Disabled: false
        Redirect IP: 
        Exclude(s):
        Include(s):
----------
Node: root
        Disabled: false
        Redirect IP: 
        Exclude(s):
        Include(s):
----------
Node: hosts
        Disabled: false
        Redirect IP: 192.168.168.1
        Exclude(s):
                rackcdn.com
                schema.org
        Include(s):
                msdn.com
                badgits.org
        Source: hpHosts
                Disabled: false
                Description: 
                Prefix: 127.0.0.0
                URL: http://www.bonzon.com
----------

&{false 192.168.168.1 [msdn.com badgits.org] [rackcdn.com schema.org] map[hpHosts:0xc420012300]}
Hello, World!
Hello, World!
Hello, World!
Hello, World!
Hello, World!
foo
--- FAIL: TestNextGeneral (0.36s)
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:17, end:19}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:19, end:20}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:20, end:23}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:23, end:24}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:24, end:26}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:26, end:31}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:31, end:23}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:23, end:24}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:24, end:26}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:26, end:31}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:31, end:23}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:23, end:24}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:24, end:26}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:26, end:27}
        integration1_test.go:215: Next for scenario servicetest.nextTest{begin:27, end:34}
        integration1_test.go:222: Program did not continue to correct next location expected 34 was 28
foo
Hello, World!
foo
Hello, World!
hi
hi
hi
hi
hi
hi
Hello, World!
hi 9
hi 9
hi 3
hi 3
hi 1
hi 1
hi 4
hi 4
hi 0
hi 0
Start
Node: root
        Disabled: false
        Redirect IP: 
        Exclude(s):
        Include(s):
----------
Node: hosts
        Disabled: false
        Redirect IP: 192.168.168.1
        Exclude(s):
                rackcdn.com
                schema.org
        Include(s):
                msdn.com
                badgits.org
        Source: hpHosts
                Disabled: false
                Description: 
                Prefix: 127.0.0.0
                URL: http://www.bonzon.com
----------
Node: domains
        Disabled: false
        Redirect IP: 
        Exclude(s):
        Include(s):
----------

&{false 192.168.168.1 [msdn.com badgits.org] [rackcdn.com schema.org] map[hpHosts:0xc420012300]}
FAIL
FAIL    github.com/derekparker/delve/service/test       53.601s
?       github.com/derekparker/delve/service/test/cmd   [no test files]
ok      github.com/derekparker/delve/terminal   3.214s
?       github.com/derekparker/delve/version    [no test files]
Makefile:65: recipe for target 'test' failed
make: *** [test] Error 1
```

Not sure if related or not.

```
go version go1.7beta2 linux/amd64

GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/florin/golang"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build907669157=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by dlsniper** [comment]
@aarzilli  / @derekparker I've pinged some of the plugin users to check it out as well. Up to you if you want to wait for them to test it out or not. Thank you once again.

**Comment by aarzilli** [comment]
> Hmm, I've ran just `make` and I've got this:

What version of go are you using? The test is different for go1.7 and go1.6, that error makes it look like we either are detecting the wrong version of go or that go1.7 changed back to go1.6 behavior. It doesn't seem a big problem and in any case it's not about this patch set because it happens in proc as well.

**Comment by dlsniper** [comment]
Using 1.7 beta 2, see at the end of the comment

**Comment by kolkov** [comment]
Fixed for me too. Thank you very much!

**Comment by renannprado** [comment]
I'm trying to test in Mac OS X, but for some reason I'm only able to run `dlv` with sudo, which is not done by IntelliJ. Can anybody help me with this?
If yes, please ping me in gophers slack channel, search for `renannp`.

**Comment by derekparker** [comment]
@renannprado hey, try using Homebrew to install Delve: https://github.com/derekparker/delve/blob/master/Documentation/installation/osx/install.md#via-homebrew -- that should correctly sign the binary and you will then be able to run without `sudo`.

**Comment by dlsniper** [comment]
@derekparker hi's trying to help testing out the patch thus the question.
However from my tests so far this seems to be working as intended.

**Comment by derekparker** [comment]
@dlsniper right, I edited to update what I meant, that I think you can use the homebrew install method to install from a different branch, and it will sign, etc and be ready for testing. Sorry for any confusion.

**Comment by renannprado** [comment]
@derekparker I'll try to find out if I can change the repository url/branch while installing with `brew`
thanks!

**Comment by ignatov** [comment]
@aarzilli @derekparker Do you have ETA for this PR?

**Comment by derekparker** [comment]
@ignatov going to take a look today, plan on getting it merged in asap.

File: service/config.go [hunk 8]
```diff
@@ -19,4 +19,6 @@ type Config struct {
 	// AcceptMulti configures the server to accept multiple connection
 	// Note that the server API is not reentrant and clients will have to coordinate
 	AcceptMulti bool
+	// ApiVersion selects which version of the API to serve (default: 1)
+	ApiVersion int
```
Comment (derekparker) [inline service/config.go]: nit: `APIVersion`

File: service/rpccommon/server.go [hunk 9]
```diff
@@ -0,0 +1,343 @@
...
+	"unicode/utf8"
+
+	"github.com/derekparker/delve/service"
+	"github.com/derekparker/delve/service/api"
+	"github.com/derekparker/delve/service/debugger"
+	"github.com/derekparker/delve/service/rpc1"
+	"github.com/derekparker/delve/service/rpc2"
+	"github.com/derekparker/delve/version"
+)
+
```
Comment (derekparker) [inline service/rpccommon/server.go]: All these exported types needs doc comments.

**Comment by derekparker** [comment]
Plan is to get this merged in by tomorrow (7/1). I have done a quick pass review, and will do a final review either tonight or tomorrow morning. Following this merging, we will likely cut a new release.

File: service/rpccommon/server.go [hunk 10]
```diff
@@ -0,0 +1,343 @@
...
+	// so we need to check the type name as well.
+	return isExported(t.Name()) || t.PkgPath() == ""
+}
+
+// Fills methods map with the methods of receiver that should be made
+// available through the RPC interface.
+// These are all the public methods of rcvr that have one of those
+// two signatures:
+// func (rcvr ReceiverType) Method(in InputType, out *ReplyType) error
+// func (rcvr ReceiverType) Method(in InputType, cb service.RPCCallback
```
Comment (derekparker) [inline service/rpccommon/server.go]: Need to fix example func signature on this line. (Missing ending paran and return type).

File: service/rpccommon/server.go [hunk 11]
```diff
@@ -0,0 +1,343 @@
...
+				log.Println("method", mname, "has wrong number of outs:", mtype.NumOut())
+				continue
+			}
+		}
+		methods[sname+"."+mname] = &methodType{method: method, ArgType: argType, ReplyType: replyType, Synchronous: synchronous, Rcvr: rcvrv}
+	}
+	return
+}
+
+func (s *ServerImpl) serveCodec(conn io.ReadWriteCloser) {
```
Comment (derekparker) [inline service/rpccommon/server.go]: nit: This isn't a generic codec, we are specifically running the json rpc codec. Maybe rename to `serveJSONCodec` to be more specific.

**Comment by derekparker** [comment]
LGTM after comments are addressed.

File: service/config.go (hunk 8 above)
Comment (aarzilli) [inline service/config.go]: I've also changed other uses of `ApiVersion` to `APIVersion` for consistency.
