### PR TITLE
proc: Increase inline function support

### LINKED ISSUE #1261: unable to process inlined functions (go1.11)
<pre>
package main

import "fmt"

func main() {
        x := &X{Foo: 10}          // line 6
        y := InlineThis(x, "bar") // line 7
        fmt.Printf("Y = %+v\n", y)
}

type X struct {
        Foo int
}

func InlineThis(x *X, s string) *X {
        xx := &X{}
        xx.Foo = x.Foo + len(s) // line 17
        return xx
}
</pre>

I expect dlv to do the right thing with optimized binaries when compiled with go1.11
but currently it is still unhappy about inlined functions.

 - funcs command doesn't recognize the inlined functions
 - can't set break point to the line where the inlined function is called (line 7).
 
I could set break points inside the inlined function though (line 16 or line 17).
'bt' from there (inside the inlined func) seemed reasonable.

<pre>
$ go build main.go
$ dlv exec ./main
Type 'help' for list of commands.
(dlv) funcs InlineThis
(dlv) b main.go:6
Breakpoint 1 set at 0x485f21 for main.main() ./main.go:6
(dlv) b main.go:7
Command failed: could not find /usr/local/google/home/hakim/go/src/s/main.go:7
(dlv) b main.go:8
Breakpoint 2 set at 0x485f4b for main.main() ./main.go:8
(dlv) b main.go:17
Breakpoint 3 set at 0x485f3f for main.main() ./main.go:17
</pre>

The versions of go, dlv I used.

<pre>
$ go version
go version devel +23ce272bb1 Mon Jul 2 17:50:00 2018 +0000 linux/amd64
$ dlv version
Delve Debugger
Version: 1.0.0
Build: bdcbd8a846eb7d4953449725ef6a23959198acf1
</pre>

### PR DESCRIPTION
**Pull request by derekparker**
This patch makes it so inlined functions are returned in the
function
list, and also allows users to set breakpoints on the call site of
inlined functions.

Fixes #1261

### CODE REVIEW

File: pkg/proc/types.go [hunk 1]
```diff
@@ -365,35 +367,75 @@ func (bi *BinaryInfo) loadDebugInfoMaps(debugLineBytes []byte, wg *sync.WaitGrou
...
+					entry, err = reader.Next()
+					if err != nil {
+						break outer
+					}
+					if entry.Tag == 0 {
+						break
+					}
+					if entry.Tag == dwarf.TagInlinedSubroutine {
+						originOffset := entry.Val(dwarf.AttrAbstractOrigin).(dwarf.Offset)
+						name := abstractOriginNameTable[originOffset]
```
Comment (aarzilli) [inline pkg/proc/types.go]: I'm worried that an inlined function will appear before its abstract entry and this won't find anything. I don't think there's anything preventing this in the standard.

File: pkg/proc/types.go [hunk 2]
```diff
@@ -365,35 +367,75 @@ func (bi *BinaryInfo) loadDebugInfoMaps(debugLineBytes []byte, wg *sync.WaitGrou
...
+						if ranges, _ := bi.dwarf.Ranges(entry); len(ranges) == 1 {
+							ok1 = true
+							lowpc = ranges[0][0]
+							highpc = ranges[0][1]
+						}
+						callfileidx := entry.Val(dwarf.AttrCallFile).(int64)
```
Comment (aarzilli) [inline pkg/proc/types.go]: both DW_AT_call_file and DW_AT_call_line are optional, go always emits them but I think we should check if they are there and skip this entry if they aren't.

File: pkg/proc/types.go (hunk 1 above)
Comment (derekparker) [reply pkg/proc/types.go]: I understand that concern but it seems unlikely. The concrete instance refers to the offset of it's abstract root, meaning that offset must already be known. Seems inefficient to make another pass to fill in the offset after if the abstract root is written later.

**Comment by derekparker** [comment]
Updated.
