### PR TITLE
proc: Fix stepping into runtime.duff*

### LINKED ISSUE #573: Step into runtime.duffzero (and runtime.duffcopy) continues instead
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
Version: 0.11.0-alpha
ede8801 Add support for Appengine; parsing Appengine Go custom version (#566)

2. What version of Go are you using? (`go version`)?
go version devel +af0fc83 Tue Jun 14 15:32:34 2016 +0000 darwin/amd64
(1.7 beta-ish; I work on the Go compiler, this is part of an exercise to be sure that 1.7 works well with delve.)

3. What operating system and processor architecture are you using?
OS X 10.11.5, amd64

4. What did you do?
Single stepped (attempted) into a call to fmt.Printf debugging this file
https://gist.github.com/dr2chase/acdd448e4fd19fdca6ab8551e55772a9#file-duffsteptest-go

5. What did you expect to see?
A step into fmt.Printf (or into a runtime support function; getting that right is another RFE)
https://gist.github.com/dr2chase/63fbe3d2275811ddde733438624c462e#file-duffsteptest_expected-txt

6. What did you see instead?
Delve continued to the end.
https://gist.github.com/dr2chase/40de9f72c7d69e125248a56e1fab5f2a#file-duffsteptest_bug-txt

I have a fix for this (that's how I generated "expected output"), I'm trying to figure out how to create a proper delve test for this.

The cause of the bug is that duffzero and duffcopy aren't regular functions and are instead called at arbitrary offsets within their bodies.  Step encounters a call, uses StepInto to get into the called function, and StepInto sets its breakpoint near the beginning and Continue()s.  Since the call itself enters well past the prologue, the breakpoint is never hit, and the process (in this case) runs to exit.  Proposed fix is to check call PC target against function entry point, if they do not match, just step.  Landing in assembly language for duffzero/copy is not best-case, but it's better than not stopping at all.

### PR DESCRIPTION
**Pull request by dr2chase**
Detect calls that do not target a function's entrypoint
(i.e, calls to runtime.duffzero and runtime.duffcopy) and
instead step into them directly.  StepInto sets a breakpoint
past the called function's prologue and expects that continue
will hit that breakpoint, but because the call is into the
interior of the function (well past the prologue) this fails.

Fixes #573

---
This change is [Reviewable](https://reviewable.io/reviews/derekparker/delve/575)

### CODE REVIEW

**Comment by dr2chase** [comment]
Any way to recheck that failure?  This is 3rd time (at least) I have attempted to do a github pull request properly, the previous two succeeded.

**Comment by aarzilli** [comment]
Delve on OS X has some known problems, the test failure there is clearly unrelated to your changes.

File: service/test/integration1_test.go [hunk 1]
```diff
@@ -945,6 +945,23 @@ func Test1NegativeStackDepthBug(t *testing.T) {
 	})
 }
 
+func Test1Issue573(t *testing.T) {
```
Comment (aarzilli) [inline service/test/integration1_test.go]: integration1_test exists to insure that we do not break backwards compatibility with the old API, things shouldn't be added to it. This test is better suited for `proc/proc_test.go`, translating it should be easy.

**Comment by dr2chase** [comment]
Oops, left out test description, will do that.

**Comment by derekparker** [comment]
Going to take a look today, was on vacation all last week. Sorry for the delay.

**Comment by derekparker** [comment]
@aarzilli from our IRC discussion I think you're referring to this PR. Can you carry over your thoughts from the mailing list onto this thread so we can discuss here please.

**Comment by aarzilli** [comment]
This is how I propose to reimplement step:

1. change the Temp field of to Kind of type breakpointKind, where breakpointKind is:

```
    type breakpointKind int
    const (
        normalBreakpoint = breakpointKind(iota)
        nextBreakpoint
        stepBreakpoint
    )
```

2. Next will create a bunch of breakpoints of kind == nextBreakpoint

3. Step will work like this:
   - disassemble all instructions belonging to the current source line
   - if we are on a CALL instruction set a breakpoint of kind == nextBreakpoint on the target and call Continue, otherwise:
   - set a breakpoint of kind == stepBreakpoint on all non-hidden CALLs (which also means all CALLs with a non-immediate destination) found in what we disassembled
   - set all the breakpoints that Next would set with kind == nextBreakpoint
   - call Continue

4. Change Continue to do this when a breakpoint of kind == stepBreakpoint is triggered
    - delete all temp breakpoints, set a new breakpoint on the target of current CALL
    - if there are no other triggered breakpoints loop, otherwise pick another CurrentThread and exit

**Comment by derekparker** [comment]
@aarzilli I'm on board with that, as from what I understand you are proposing removing the current `SingleStep` implementation and instead going with the `Next`-style implementation, correct?

> set a breakpoint of kind == stepBreakpoint on all non-hidden CALLs (which also means all CALLs with a non-immediate destination) found in what we disassembled

So this is what would satisfy this bug if I understand correctly, since we're setting a breakpoint on non-immediate destinations such as these computed jumps into duff* functions, correct?

We're still going to need logic to determine if where we are jumping into is equal to the function entrypoint, as we want to skip the looping prologue. 

Correct me if I am misunderstanding anything. If that is the case, I am leaning towards merging this fix in for the time being, with the understanding that Step/StepInto will be updated with the logic you describe.

**Comment by aarzilli** [comment]
> So this is what would satisfy this bug if I understand correctly, since we're setting a breakpoint on non-immediate destinations such as these computed jumps into duff* functions, correct?

duff* stuff are private runtime functions, so I would just skip them, at least by default. But besides that, yes.

> Correct me if I am misunderstanding anything. If that is the case, I am leaning towards merging this fix in for the time being, with the understanding that Step/StepInto will be updated with the logic you describe.

Makes sense. I would have pulled code from this patch anyway.

**Comment by aarzilli** [comment]
BTW, in chat I was referring to #565, my PR concerning Step, not this PR.
