### PR TITLE
terminal: disable file path case normalization on macOS

### LINKED ISSUE #1088: path error when case-sensitive apfs on macOS
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.0.0-rc.2
Build: v1.0.0-rc.2

2. What version of Go are you using? (`go version`)?
go version go1.9.2 darwin/amd64

3. What operating system and processor architecture are you using?
macOS 10.13.2 (case-sensitive apfs)

4. What did you do?
debug a go application.

5. What did you expect to see?
(dlv) ls
Stopped at: 0x1459119c
=>no source available
Command failed: open : no such file or directory
(dlv)

6. What did you see instead?
show source code.

I guess caused by case-sensitive apfs.

### PR DESCRIPTION
**Pull request by aarzilli**
```
terminal: disable file path case normalization on macOS

Fixes #1088

```

### CODE REVIEW

**Comment by derekparker** [comment]
OSX tests are failing.

**Comment by aarzilli** [comment]
Fixed

File: pkg/terminal/terminal_test.go [hunk 1]
```diff
@@ -39,7 +39,7 @@ func platformCases() []tCase {
 	}
 	casesDarwin := []tCase{
 		// Should be case-insensitive
```
Comment (derekparker) [inline pkg/terminal/terminal_test.go]: nit: Update this comment.
