### PR TITLE
fixes #1450 vim and neovim fail to load with the 'edit' command

### LINKED ISSUE #1450: 'edit' command failing with 'Command Failed: exit status 1'
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
1.1.0
2. What version of Go are you using? (`go version`)?
go1.11.2 linux/amd64
3. What operating system and processor architecture are you using?
Ubuntu cosmic
4. What did you do?
set environment variables
EDITOR=/usr/bin/nvim
DELVE_EDITOR=/usr/bin/nvim
debugged to a breakpoint and ran 'edit' command
5. What did you expect to see?
neovim opened at given line
6. What did you see instead?
Command Failed: exit status 1

I have recompiled `dlv` to output the values of the command and arguments at line https://github.com/derekparker/delve/blob/master/pkg/terminal/command.go#L1218 and all looks good. I can run this command locally in bash and it works fine, but not from within dlv. Similarly setting the value to `/usr/bin/vim` also fails with the same error.

### PR DESCRIPTION
**Pull request by the4thamigo-uk**

### CODE REVIEW

File: pkg/terminal/command.go [hunk 1]
```diff
@@ -1216,6 +1216,8 @@ func edit(t *Term, ctx callContext, args string) error {
 	}
 
 	cmd := exec.Command(editor, fmt.Sprintf("+%d", lineno), file)
+	cmd.Stdin = os.Stdin
+	cmd.Stdout = os.Stdout
```
Comment (aarzilli) [inline pkg/terminal/command.go]: let's do stderr to: `cmd.Stderr = os.Stderr`.

Comment (the4thamigo-uk) [reply pkg/terminal/command.go]: ok
