### PR TITLE
miscellaneous proc/native cleanups

### LINKED ISSUE #1101: Problems when following a non-main goroutine with 'next' command: Delve doesn't detect the end of the program
Playing with a basic [goroutine example](https://gobyexample.com/goroutines) to add it to the getting started guide I came across a series of panics and hangs (that I believe are all related) when switching to a non-`main` goroutine and following it with `next`, because (I'm guessing) Delve at some point misses the end of the program and pointers like `(*Thread)` in the server or `DebuggerState.CurrentThread` in the client are `nil`. I'll be looking deeper into this issue but I document it here to get some feedback about it.

The problem, as it deals with threads and goroutines, is not completely deterministic but comes up often enough (at least in my machine) that after a couple of tries it will manifest itself (in different ways). In it most basic form the test code is an empty main function that spawns a goroutine (also empty) and waits for it (the `sync.Wait` was added to the cited example):

```go
package main

import (
    "sync"
)

var wg sync.WaitGroup

func f(from string) {
    defer wg.Done()
    return
}

func main() {
    wg.Add(1)
    go f("goroutine")
    wg.Wait()
}
```

Building the binary

```
$ dlv debug --output debug_binary
```

and running the following CLI commands that break inside the function executed by the goroutine (with an implicit goroutine switch)

```
r
b main.main
c
b f
c
n # repeated three times to exit f() goroutine
n
n
```

leaves it inside the created goroutine

```
     8:	
=>   9:	func f(from string) {
    10:	    defer wg.Done()
    11:	    return
    12:	}
    13:	
    14:	func main() {
(dlv) goroutines
[4 goroutines]
  Goroutine 1 - User: /usr/local/go/src/runtime/sema.go:56 sync.runtime_Semacquire (0x4350b9)
  Goroutine 2 - User: /usr/local/go/src/runtime/proc.go:288 runtime.gopark (0x427b2d)
  Goroutine 17 - User: /usr/local/go/src/runtime/proc.go:288 runtime.gopark (0x427b2d)
* Goroutine 18 - User: ./main.go:9 main.f (0x455f1f) (thread 21588)
(dlv) 
```

From this point, following the execution with the `next` command sometimes ends correctly with the process termination, but in other cases it results in panics or hangs. Alternatively, using the command `continue` always ends correctly without issues.

Problem 1: panic in the terminal client.

```
No current thread available
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7be5fb]

goroutine 1 [running]:
github.com/derekparker/delve/pkg/terminal.continueUntilCompleteNext(0xc420061e60, 0xc4204362a0, 0xaecfb2, 0x4, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/command.go:749 +0x20b
github.com/derekparker/delve/pkg/terminal.next(0xc420061e60, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0, 0x2, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/command.go:823 +0x116
github.com/derekparker/delve/pkg/terminal.(*Commands).CallWithContext(0xc420171d40, 0xc420293bec, 0x0, 0xc420061e60, 0x0, 0xffffffffffffffff, 0x0, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/command.go:348 +0x12a
github.com/derekparker/delve/pkg/terminal.(*Commands).Call(0xc420171d40, 0xc420293bec, 0x0, 0xc420061e60, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/command.go:353 +0x71
github.com/derekparker/delve/pkg/terminal.(*Term).Run(0xc420061e60, 0x0, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/pkg/terminal/terminal.go:132 +0x33c
github.com/derekparker/delve/cmd/dlv/cmds.execute(0x0, 0xc42014e3b0, 0x1, 0x1, 0xc420156240, 0x0, 0x0, 0x1, 0x0)
	/home/user/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:537 +0x8e3
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd.func1(0xc420172900, 0xc42014c480, 0x0, 0x2, 0x0)
	/home/user/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:300 +0x405
github.com/derekparker/delve/cmd/dlv/cmds.debugCmd(0xc420172900, 0xc42014c480, 0x0, 0x2)
	/home/user/go/src/github.com/derekparker/delve/cmd/dlv/cmds/commands.go:301 +0x49
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).execute(0xc420172900, 0xc42014c300, 0x2, 0x2, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:647 +0xa4e
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420172240, 0xc420172900, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:733 +0x68c
github.com/derekparker/delve/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420172240, 0x0, 0x0)
	/home/user/go/src/github.com/derekparker/delve/vendor/github.com/spf13/cobra/command.go:692 +0x4f
main.main()
	/home/user/go/src/github.com/derekparker/delve/cmd/dlv/main.go:18 +0x91

```

Problem 2: panic in the debugger server when restarting what appeared to be a correct end in the execution

```
(dlv) r
Command failed: Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.call32 (0x45ceba)
	/usr/local/go/src/runtime/asm_amd64.s:509
runtime.gopanic (0x42f541)
	/usr/local/go/src/runtime/panic.go:491
runtime.panicmem (0x42e41d)
	/usr/local/go/src/runtime/panic.go:63
runtime.sigpanic (0x44649b)
	/usr/local/go/src/runtime/signal_unix.go:367
github.com/derekparker/delve/pkg/proc/native.(*Thread).stopped (0x797392)
	/home/user/go/src/github.com/derekparker/delve/pkg/proc/native/threads_linux.go:34
github.com/derekparker/delve/pkg/proc/native.(*Thread).Stopped (0x796a8a)
	/home/user/go/src/github.com/derekparker/delve/pkg/proc/native/threads.go:120
github.com/derekparker/delve/pkg/proc/native.(*Process).Kill (0x7916fd)
	/home/user/go/src/github.com/derekparker/delve/pkg/proc/native/proc_linux.go:106
github.com/derekparker/delve/pkg/proc/native.(*Process).Detach (0x78ee2e)
	/home/user/go/src/github.com/derekparker/delve/pkg/proc/native/proc.go:82
github.com/derekparker/delve/service/debugger.(*Debugger).detach (0x79a61b)
	/home/user/go/src/github.com/derekparker/delve/service/debugger/debugger.go:177
github.com/derekparker/delve/service/debugger.(*Debugger).Restart (0x79a78d)
	/home/user/go/src/github.com/derekparker/delve/service/debugger/debugger.go:203
github.com/derekparker/delve/service/rpc2.(*RPCServer).Restart (0x977f87)
	/home/user/go/src/github.com/derekparker/delve/service/rpc2/server.go:83
runtime.call128 (0x45cfd1)
	/usr/local/go/src/runtime/asm_amd64.s:511
reflect.Value.call (0x4e21b5)
	/usr/local/go/src/reflect/value.go:434
reflect.Value.Call (0x4e1366)
	/usr/local/go/src/reflect/value.go:302
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func1 (0x98095d)
	/home/user/go/src/github.com/derekparker/delve/service/rpccommon/server.go:299
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0x97f52d)
	/home/user/go/src/github.com/derekparker/delve/service/rpccommon/server.go:301
runtime.goexit (0x45f6e0)
	/usr/local/go/src/runtime/asm_amd64.s:2337
```

Problem 3: Delve hangs with a zombie process.

```
$ command ps aux -T | grep debug_bin
user     15052 15052  0.0  0.0      0     0 pts/18   Zl   08:58   0:00 [debug_binary] <defunct>
user     15052 15053  0.0  0.0      0     0 pts/18   Zl   08:58   0:00 [debug_binary] <defunct>
user     15052 15054  0.0  0.0      0     0 pts/18   Zl   08:58   0:00 [debug_binary] <defunct>
```

Removing the `Wait` call in `main`, although it makes it less probable that Delve will hit the breakpoint inside the goroutine (because `main` ends before that), when it does, it always (or very likely) causes one of the above described problems because (I'm guessing again) Delve is not detecting the end of the `main` goroutine while stepping through the (now dead) non-`main` goroutine. (To increase the probability of hitting the breakpoint the removed `Println` statement from the cited example should be added again to the function executed by the goroutine.)

Development environment:

```
go version go1.9.2 linux/amd64
Delve Debugger
Version: 1.0.0-rc.2
Build: 74d330a013a5412649aaa069d932b93889c2dbd2
```

### PR DESCRIPTION
**Pull request by aarzilli**
* Removes proc.Process.Kill, it was only used by tests at this point
* Removes proc.Process.Halt, fuses the Halt in proc/native with native's setCurrentBreakpoints into a single stop method. Halt wasn't used outside of native and some tests, and it was redundant with RequestManualStop.
* Moves the fields Process.halt and Thread.running in native to os specific structs and removes them from all operating system implementations that don't actually make use of them.

### CODE REVIEW

**Comment by derekparker** [comment]
Looks good so far, liking the direction and will be a good base for cleanup of proc.

File: pkg/proc/native/proc_darwin.go [hunk 1]
```diff
@@ -446,6 +426,38 @@ func (dbp *Process) resume() error {
 	return nil
 }
 
+// stop stops all running threads threads and sets breakpoints
```
Comment (derekparker) [inline pkg/proc/native/proc_darwin.go]: nit: wrote "threads" twice.

File: pkg/proc/native/proc_darwin.go [hunk 2]
```diff
@@ -446,6 +426,38 @@ func (dbp *Process) resume() error {
...
+func (dbp *Process) stop(trapthread *Thread) (err error) {
+	if dbp.exited {
+		return &proc.ProcessExitedError{Pid: dbp.Pid()}
+	}
+	for _, th := range dbp.threads {
+		if !th.Stopped() {
+			if err := th.halt(); err != nil {
```
Comment (derekparker) [inline pkg/proc/native/proc_darwin.go]: nit: Let's be consistent with naming and call both `stop` or `halt`. I'm leaning towards `halt` because we also have that flag on the OS struct as well.

File: pkg/proc/native/proc.go [hunk 3]
```diff
@@ -33,7 +33,6 @@ type Process struct {
 	os                  *OSProcessDetails
 	firstStart          bool
 	haltMu              sync.Mutex
```
Comment (derekparker) [inline pkg/proc/native/proc.go]: nit: We should change this to `stopMux`.

File: pkg/proc/native/proc_darwin.go [hunk 4]
```diff
@@ -25,6 +25,7 @@ type OSProcessDetails struct {
 	exceptionPort    C.mach_port_t // mach port for receiving mach exceptions.
 	notificationPort C.mach_port_t // mach port for dead name notification (process exit).
 	initialized      bool
+	halt             bool
```
Comment (derekparker) [inline pkg/proc/native/proc_darwin.go]: I like the approach for linux where this is no longer state set but rather passed into `trapWaitInternal`. What are your thoughts on doing something similar here?

File: pkg/proc/native/proc_darwin.go (hunk 2 above)
Comment (aarzilli) [reply pkg/proc/native/proc_darwin.go]: It was called halt before but it did a different thing, given that the meaning changed the name should change too, IMHO.

File: pkg/proc/native/proc_darwin.go (hunk 4 above)
Comment (aarzilli) [reply pkg/proc/native/proc_darwin.go]: Ideally, yes. In practice I don't want to spend time figuring out how to do it, since we are not using it.

File: pkg/proc/native/proc_darwin.go (hunk 2 above)
Comment (derekparker) [reply pkg/proc/native/proc_darwin.go]: Are you in favor of switching consistently to `stop`?

Comment (aarzilli) [reply pkg/proc/native/proc_darwin.go]: Done.
