### PR TITLE
proc: do not panic if we can't satisfy a composite location for a slice var

### LINKED ISSUE #1419: Runtime error in proc.(*compositeMemory).ReadMemory.
1. What version of Delve are you using (`dlv version`)?
Delve Debugger
Version: 1.1.0
Build: 85e4ba439cf0b206f5b63836b166cffe9516312e (HEAD on master at time of writing)

2. What version of Go are you using? (`go version`)?
go version go1.11.2 linux/amd64

3. What operating system and processor architecture are you using?
GNU/Linux x86_64

4. What did you do?
Set breakpoint from Goland IDE, debug tests, and hit breakpoint.

5. What did you expect to see?
A stack back trace report in the "Frames" view.

6. What did you see instead?
A panic from github.com/derekparker/delve/pkg/proc.(*compositeMemory).ReadMemory. I did some testing and discovered that the error stems from the fact that the 'mem' struct (the receiver) is nil. Inserting this into the function (before line 121 in mem.go) avoids the panic.
```
if mem == nil {
  return 0, errors.New("no mem")
}
```
Excerpt from the ideal.log showing the panic:
```
org.jetbrains.concurrency.InternalPromiseUtil$MessageError: Internal debugger error: runtime error: invalid memory address or nil pointer dereference
runtime.call32 (0x4579da)
	/usr/local/go/src/runtime/asm_amd64.s:522
runtime.gopanic (0x42c0f8)
	/usr/local/go/src/runtime/panic.go:513
runtime.panicmem (0x42b24d)
	/usr/local/go/src/runtime/panic.go:82
runtime.sigpanic (0x441611)
	/usr/local/go/src/runtime/signal_unix.go:390
github.com/derekparker/delve/pkg/proc.(*compositeMemory).ReadMemory (0x6a8039)
	/home/thhal/go/src/github.com/derekparker/delve/pkg/proc/mem.go:121
github.com/derekparker/delve/pkg/proc.readUintRaw (0x6cd275)
	/home/thhal/go/src/github.com/derekparker/delve/pkg/proc/variables.go:1449
github.com/derekparker/delve/pkg/proc.(*Variable).loadSliceInfo (0x6cb935)
	/home/thhal/go/src/github.com/derekparker/delve/pkg/proc/variables.go:1233
github.com/derekparker/delve/pkg/proc.newVariable (0x6c46d5)
	/home/thhal/go/src/github.com/derekparker/delve/pkg/proc/variables.go:301
github.com/derekparker/delve/pkg/proc.(*EvalScope).newVariable (0x6c4024)
	/home/thhal/go/src/github.com/derekparker/delve/pkg/proc/variables.go:231
github.com/derekparker/delve/pkg/proc.(*EvalScope).extractVarInfoFromEntry (0x6c9147)
	/home/thhal/go/src/github.com/derekparker/delve/pkg/proc/variables.go:917
github.com/derekparker/delve/pkg/proc.(*EvalScope).Locals (0x6d1096)
	/home/thhal/go/src/github.com/derekparker/delve/pkg/proc/variables.go:2103
github.com/derekparker/delve/pkg/proc.(*EvalScope).LocalVariables (0x6c6f6e)
	/home/thhal/go/src/github.com/derekparker/delve/pkg/proc/variables.go:685
github.com/derekparker/delve/service/debugger.(*Debugger).convertStacktrace (0x72926e)
	/home/thhal/go/src/github.com/derekparker/delve/service/debugger/debugger.go:974
github.com/derekparker/delve/service/debugger.(*Debugger).Stacktrace (0x728bd3)
	/home/thhal/go/src/github.com/derekparker/delve/service/debugger/debugger.go:952
github.com/derekparker/delve/service/rpc2.(*RPCServer).Stacktrace (0x8c6358)
	/home/thhal/go/src/github.com/derekparker/delve/service/rpc2/server.go:176
runtime.call64 (0x457a5a)
	/usr/local/go/src/runtime/asm_amd64.s:523
reflect.Value.call (0x4b2318)
	/usr/local/go/src/reflect/value.go:447
reflect.Value.Call (0x4b1db3)
	/usr/local/go/src/reflect/value.go:308
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec.func2 (0x8ceb4c)
	/home/thhal/go/src/github.com/derekparker/delve/service/rpccommon/server.go:321
github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec (0x8cd06b)
	/home/thhal/go/src/github.com/derekparker/delve/service/rpccommon/server.go:323
runtime.goexit (0x4596f0)
	/usr/local/go/src/runtime/asm_amd64.s:1333
```

### PR DESCRIPTION
**Pull request by aarzilli**
```
proc: do not panic if we can't satisfy a composite location for a slice var

The fix in 7f53117 for Issue #1416 had a bug, fix it and add a test.

Fixes #1419

```

### CODE REVIEW

File: pkg/dwarf/dwarfbuilder/info.go [hunk 1]
```diff
@@ -282,3 +283,12 @@ func (b *Builder) AddMember(fieldname string, typ dwarf.Offset, memberLoc []byte
 	b.TagClose()
 	return r
 }
+
+// AddStructType adds a new pointer type to debug_info.
+func (b *Builder) AddPointerType(typename string, typ dwarf.Offset) dwarf.Offset {
```
Comment (derekparker) [inline pkg/dwarf/dwarfbuilder/info.go]: Doc string is wrong.
