### PR TITLE
Fix for #614 and #683

### LINKED ISSUE #614: Delve should detach from the target process before crashing
See https://github.com/derekparker/delve/issues/79#issuecomment-240239269

### LINKED ISSUE #683: step panics if source file isn't found in .debug_line
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)? The latest one from the master.
2. What version of Go are you using? (`go version`)? 1.7.1
3. What operating system and processor architecture are you using?
4. What did you do?

```go
package main

import "fmt"

func main() {
	fmt.Println("adssd") // put a breakpoint here
}
```

and step into until you'll get the exception.

5. What did you expect to see?

6. What did you see instead?

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x42caf41]

goroutine 43 [running]:
panic(0x44a8000, 0xc4200140a0)
	/Users/builduser/buildAgent/work/d46533bce70e485f/go/src/runtime/panic.go:500 +0x1a1
github.com/derekparker/delve/dwarf/line.(*DebugLines).AllPCsBetween(0xc42008bed8, 0x7ca90, 0x7ca94, 0x0, 0x0, 0x1, 0x1, 0x0)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/dwarf/line/state_machine.go:114 +0xb1
github.com/derekparker/delve/proc.(*Process).next(0xc42008be60, 0xc420122601, 0x27290, 0xc42008d1b8)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/proc/threads.go:236 +0x597
github.com/derekparker/delve/proc.(*Process).Step(0xc42008be60, 0x1, 0x1)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/proc/proc.go:454 +0xfe
github.com/derekparker/delve/service/debugger.(*Debugger).Command(0xc4200dd800, 0xc4207d1b48, 0x0, 0x0, 0x0)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/service/debugger/debugger.go:421 +0x515
github.com/derekparker/delve/service/rpc2.(*RPCServer).Command(0xc4201981d0, 0xc4207059b8, 0x4, 0x0, 0x0, 0x4d1faf0, 0xc4201a9540)
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/service/rpc2/server.go:85 +0x51
reflect.Value.call(0xc420244b40, 0xc420132330, 0x13, 0x4527879, 0x4, 0xc420534050, 0x3, 0x3, 0x339, 0x745d9, ...)
	/Users/builduser/buildAgent/work/d46533bce70e485f/go/src/reflect/value.go:434 +0x5c8
reflect.Value.Call(0xc420244b40, 0xc420132330, 0x13, 0xc420534050, 0x3, 0x3, 0x0, 0x0, 0x370)
	/Users/builduser/buildAgent/work/d46533bce70e485f/go/src/reflect/value.go:302 +0xa4
created by github.com/derekparker/delve/service/rpccommon.(*ServerImpl).serveJSONCodec
	/Users/builduser/buildAgent/work/d46533bce70e485f/gopath/src/github.com/derekparker/delve/service/rpccommon/server.go:299 +0xa38
```

### PR DESCRIPTION
**Pull request by aarzilli**
service: Prevent panics from crashing delve and killing the target

Catch all unrecovered proc and debugger panics in the service layer and
report them as errors, allow users to cleanly detach from the target
and quit.

Fixes #614

proc: Next/Step should not panic if line info can not be found.

Fixes #683

### CODE REVIEW

**Comment by derekparker** [comment]
@aarzilli overall looks fine, but pretty much every test on OSX is failing now.

**Comment by aarzilli** [comment]
The problem on macOS is because of the 10.12.1 patch, not this PR. I don't have the exact version of macOS that travis is running (10.11) and it doesn't happen on the versions I have (10.10 and 10.12).

File: proc/proc_test.go [hunk 1]
```diff
@@ -2357,3 +2357,20 @@ func TestNegativeIntEvaluation(t *testing.T) {
...
+	// Step panics when source file can not be found
+	withTestProcess("issue683", t, func(p *Process, fixture protest.Fixture) {
+		_, err := setFunctionBreakpoint(p, "main.main")
+		assertNoError(err, t, "setFunctionBreakpoint()")
+		assertNoError(p.Continue(), t, "First Continue()")
+		for i := 0; i < 20; i++ {
+			// eventually an error about the source file not being found will be
+			// returned, the important thing is that we shouldn't panic
+			err := p.Step()
+			if err != nil {
```
Comment (derekparker) [inline proc/proc_test.go]: We should set some sort of state here that if we never get an error, the test should fail.

Comment (aarzilli) [inline proc/proc_test.go]: Done.
