### PR TITLE
proc: Implement Step using Continue 

### LINKED ISSUE #561: proc.(*Process).Step doesn't make progress when on a CALL instruction where a breakpoint is also set
Please answer the following before submitting your issue:

Note: Please include any substantial examples (debug session output,
stacktraces, etc) as linked gists.

1. What version of Delve are you using (`dlv version`)?
0.11.0-alpha

2. What version of Go are you using? (`go version`)?
1.6.2

3. What operating system and processor architecture are you using?
linux/amd64

4. Issue: When debug `swarm` in step mode, the `dlv` will create goroutines endlessly:  

```
# dlv debug github.com/docker/swarm create
Type 'help' for list of commands.
(dlv) b main.main
Breakpoint 1 set at 0x40100f for main.main() ./src/github.com/docker/swarm/main.go:13
(dlv) c
> main.main() ./src/github.com/docker/swarm/main.go:13 (hits goroutine(1):1 total:1) (PC: 0x40100f)
     8:
     9:         "github.com/docker/swarm/cli"
    10: )
    11:
    12: func main() {
=>  13:         cli.Run()
    14: }
(dlv) s
> main.main() ./src/github.com/docker/swarm/main.go:13 (hits goroutine(1):2 total:2) (PC: 0x40100f)
     8:
     9:         "github.com/docker/swarm/cli"
    10: )
    11:
    12: func main() {
=>  13:         cli.Run()
    14: }
(dlv) s
> main.main() ./src/github.com/docker/swarm/main.go:13 (hits goroutine(1):3 total:3) (PC: 0x40100f)
     8:
     9:         "github.com/docker/swarm/cli"
    10: )
    11:
    12: func main() {
=>  13:         cli.Run()
    14: }
(dlv) s
> main.main() ./src/github.com/docker/swarm/main.go:13 (hits goroutine(1):4 total:4) (PC: 0x40100f)
     8:
     9:         "github.com/docker/swarm/cli"
    10: )
    11:
    12: func main() {
=>  13:         cli.Run()
    14: }
(dlv) s
> main.main() ./src/github.com/docker/swarm/main.go:13 (hits goroutine(1):5 total:5) (PC: 0x40100f)
     8:
     9:         "github.com/docker/swarm/cli"
    10: )
    11:
    12: func main() {
=>  13:         cli.Run()
    14: }
(dlv) s
> main.main() ./src/github.com/docker/swarm/main.go:13 (hits goroutine(1):6 total:6) (PC: 0x40100f)
     8:
     9:         "github.com/docker/swarm/cli"
    10: )
    11:
    12: func main() {
=>  13:         cli.Run()
    14: }
......

```

### PR DESCRIPTION
**Pull request by aarzilli**
Instead of repeatedly calling StepInstruction set breakpoints to the
destination of CALL instructions (or on the CALL instructions
themselves for indirect CALLs), then call Continue.
Calls to unexported runtime functions are skipped.
Reduces the number of code paths managing inferior state from 3 to 2
(StepInstruction, Continue).

Fixes #561

---
This change is [Reviewable](https://reviewable.io/reviews/derekparker/delve/603)

### CODE REVIEW

**Comment by derekparker** [comment]
You have a binary committed under `_fixtures` that needs to be removed.

File: proc/breakpoints.go [hunk 1]
```diff
@@ -33,9 +33,33 @@ type Breakpoint struct {
...
+	// is in the DeferReturns array.
+	// Next sets DeferCond for the breakpoint it sets on the
+	// deferred function, DeferReturns is populated with the
+	// addresses of calls to runtime.deferreturn in the current
+	// function. This insures that the breakpoint on the deferred
+	// function only triggers on panic or on the defer call to
+	// the function, not when the function is called directly
+	DeferCond    bool
+	DeferReturns []uint64
+	Cond         ast.Expr // When Cond is not nil the breakpoint will be triggered only if evaluating Cond returns true
```
Comment (derekparker) [inline proc/breakpoints.go]: nit: Move this comment above the member, and drop the initial `When`, and say something like `Cond, if not nil, ...`

File: proc/breakpoints.go [hunk 2]
```diff
@@ -33,9 +33,33 @@ type Breakpoint struct {
...
 }
 
+type BreakpointKind int
+
+const (
```
Comment (derekparker) [inline proc/breakpoints.go]: nit: Start comment w/ name of exported const, even if redundant.

File: proc/proc.go [hunk 3]
```diff
@@ -327,11 +326,31 @@ func (dbp *Process) Continue() error {
...
+					return err
+				}
+				text, err := dbp.CurrentThread.Disassemble(pc, pc+maxInstructionLength, true)
+				if err != nil {
+					return err
+				}
+				if err = dbp.setStepIntoBreakpoint(text, sameGoroutineCondition(dbp.SelectedGoroutine)); err != nil {
+					return err
+				}
+				// here we either set a breakpoint into the destination of the CALL
```
Comment (derekparker) [inline proc/proc.go]: This comment seems out of place.

File: proc/proc.go [hunk 4]
```diff
@@ -388,65 +407,29 @@ func (dbp *Process) pickCurrentThread(trapthread *Thread) error {
 // Step will continue until another source line is reached.
 // Will step into functions.
 func (dbp *Process) Step() (err error) {
```
Comment (derekparker) [inline proc/proc.go]: Much better! Way cleaner.

File: proc/proc.go [hunk 5]
```diff
@@ -388,65 +407,29 @@ func (dbp *Process) pickCurrentThread(trapthread *Thread) error {
...
 	}
-	pc, _ := dbp.FirstPCAfterPrologue(fn, false)
-	return dbp.stepToPC(pc)
+
+	return dbp.Continue()
 }
 
 func (dbp *Process) stepToPC(pc uint64) error {
-	if _, err := dbp.SetTempBreakpoint(pc, sameGoroutineCondition(dbp.SelectedGoroutine)); err != nil {
+	if _, err := dbp.SetTempBreakpoint(pc, NextBreakpoint, sameGoroutineCondition(dbp.SelectedGoroutine)); err != nil {
```
Comment (derekparker) [inline proc/proc.go]: Don't have to address here but do we even still need `SetTempBreakpoint` anymore? We should just assign the breakpoint type in the caller (as we're doing anyways) and have a single `SetBreakpoint` method. Could potentially get tricky w/ how we increment breakpoint counts, and would add some more logic there (e.g. increment only for a "normal" breakpoint).

File: proc/proc.go [hunk 6]
```diff
@@ -740,37 +732,21 @@ func initializeDebugProcess(dbp *Process, path string, attach bool) (*Process, e
 
 func (dbp *Process) ClearTempBreakpoints() error {
 	for _, bp := range dbp.Breakpoints {
-		if !bp.Temp {
+		if bp.Kind == NormalBreakpoint {
```
Comment (derekparker) [inline proc/proc.go]: Maybe we add a method to `Breakpoint` such as `Temp() bool` which encapsulates this logic? Just a minor nit.

File: proc/breakpoints.go [hunk 7]
```diff
@@ -33,9 +33,33 @@ type Breakpoint struct {
...
+	// User set breakpoint
+	NormalBreakpoint BreakpointKind = iota
```
Comment (derekparker) [inline proc/breakpoints.go]: nit: s/NormalBreakpoint/UserBreakpoint/ or something to that effect.

File: proc/proc.go (hunk 6 above)
Comment (derekparker) [inline proc/proc.go]: Maybe not `Temp()` but maybe `Internal()` or something to say that it was not set by a user and is for the debuggers own internal user.

File: proc/threads.go [hunk 8]
```diff
@@ -145,73 +146,167 @@ func topframe(g *G, thread *Thread) (Stackframe, error) {
...
+func (dbp *Process) next(stepInto bool) error {
 	topframe, err := topframe(dbp.SelectedGoroutine, dbp.CurrentThread)
 	if err != nil {
 		return err
 	}
 
-	if filepath.Ext(topframe.Current.File) != ".go" {
-		return dbp.cnext(topframe)
+	csource := filepath.Ext(topframe.Current.File) != ".go"
+
```
Comment (derekparker) [inline proc/threads.go]: nit: remove blank line

File: proc/threads.go [hunk 9]
```diff
@@ -145,73 +146,167 @@ func topframe(g *G, thread *Thread) (Stackframe, error) {
...
+		if dbp.SelectedGoroutine != nil && dbp.SelectedGoroutine.DeferPC != 0 {
+			_, _, deferfn := dbp.goSymTable.PCToLine(dbp.SelectedGoroutine.DeferPC)
+			var err error
+			deferpc, err = dbp.FirstPCAfterPrologue(deferfn, false)
+			if err != nil {
+				return err
+			}
+		}
+		if deferpc != 0 && deferpc != topframe.Current.PC {
+			bp, err := dbp.SetTempBreakpoint(deferpc, NextBreakpoint, cond)
```
Comment (derekparker) [inline proc/threads.go]: What do you think about having a `NextDeferBreakpoint` type and removing the `DeferCond` member?

File: proc/threads.go [hunk 10]
```diff
@@ -145,73 +146,167 @@ func topframe(g *G, thread *Thread) (Stackframe, error) {
...
 		}
 	}
-	if deferpc != 0 {
-		pcs = append(pcs, deferpc)
+
+	// Add breakpoints on all the lines in the current function
+	pcs := dbp.lineInfo.AllPCsBetween(topframe.FDE.Begin(), topframe.FDE.End()-1, topframe.Current.File)
+
+	if !csource {
+		var covered bool
```
Comment (derekparker) [inline proc/threads.go]: I know this is carry over, but it would be nice to have some comments here explaining this logic.

File: proc/threads.go [hunk 11]
```diff
@@ -145,73 +146,167 @@ func topframe(g *G, thread *Thread) (Stackframe, error) {
...
+
+	// Ensure PC and Entry match, otherwise StepInto is likely to set
+	// its breakpoint before DestLoc.PC and hence run too far ahead.
+	// Calls to runtime.duffzero and duffcopy have this problem.
+	if fn.Entry != instr.DestLoc.PC {
+		return nil
+	}
+
+	// Skip unexported runtime functions
+	if strings.HasPrefix(fn.Name, "runtime.") && !isExportedRuntime(fn.Name) {
```
Comment (derekparker) [inline proc/threads.go]: Can omit the first condition (`strings.HasPrefix(fn.Name, "runtime.")`) that is done by `isExportedRuntime`.

Comment (derekparker) [inline proc/threads.go]: Additionally, we should allow user control over this. Maybe not in this PR, but certainly it should be opt-out-able.

File: proc/threads.go [hunk 12]
```diff
@@ -358,12 +453,18 @@ func (thread *Thread) SetCurrentBreakpoint() error {
 	return nil
 }
 
+func (thread *Thread) resetBreakpoint() {
```
Comment (derekparker) [inline proc/threads.go]: nit: rename to something like: `clearBreakpointState` or something along those lines to make it clear it's basically just zeroing out it's own state.

**Comment by derekparker** [comment]
Done w/ this review pass. Haven't checked on CI, but they have been flickering a lot (very annoying, we need to fully solve that) so I'll see what CI is doing once you push again.

File: proc/proc.go (hunk 5 above)
Comment (aarzilli) [inline proc/proc.go]: Agreed. What do you think of this signature:
```
func (dbp *Process) SetBreakpoint(addr uint64, kind BreakpointKind, cond ast.Expr) (*Breakpoint, error)
```

The counters are handled by `(*Process).setBreakpoint` anyway, that's not a problem. I would do this on another commit however. I'd do it in a separate PR, however.

File: proc/threads.go (hunk 9 above)
Comment (aarzilli) [inline proc/threads.go]: Sounds better.

File: proc/threads.go (hunk 10 above)
Comment (aarzilli) [inline proc/threads.go]: To be honest I don't understand the logic of that, you'll have to fill me in.

File: proc/threads.go (hunk 11 above)
Comment (aarzilli) [inline proc/threads.go]: If I omit the `strings.HasPrefix(fn.Name, "runtime.")` we hide everything except exported runtime functions, what we want is hide all runtime functions except the ones that are exported.

**Comment by aarzilli** [comment]
Appveyor started flickering because they switched us to a multicore VM, #598 should take care of that. The rest is the usual OS X flicker we've always had, I don't think there are new bugs.

**Comment by aarzilli** [comment]
Done and rebased on master.

File: proc/breakpoints.go [hunk 13]
```diff
@@ -33,9 +33,39 @@ type Breakpoint struct {
...
+	// addresses of calls to runtime.deferreturn in the current
+	// function. This insures that the breakpoint on the deferred
+	// function only triggers on panic or on the defer call to
+	// the function, not when the function is called directly
+	DeferReturns []uint64
+	// Cond: if not nil the breakpoint will be triggered only if evaluating Cond returns true
+	Cond ast.Expr
 }
 
+type BreakpointKind int
```
Comment (derekparker) [inline proc/breakpoints.go]: nit: Exported type needs doc string.

File: proc/breakpoints.go [hunk 14]
```diff
@@ -139,6 +187,10 @@ func (bp *Breakpoint) checkCondition(thread *Thread) (bool, error) {
 	return constant.BoolVal(v.Value), nil
 }
 
+func (bp *Breakpoint) Internal() bool {
```
Comment (derekparker) [inline proc/breakpoints.go]: nit: Add doc comment.

**Comment by aarzilli** [comment]
Done and rebased.
